### ISSUE TITLE
[BUG] Name change GraphSQL error

### ISSUE THREAD

**Issue by DavidsBees** [cobudget/cobudget#1004]
**Describe the bug**
When changing the name in profile settings a graph SQL error appears but the action seems to work

![image](https://user-images.githubusercontent.com/80971095/236440364-8eea87d4-e381-4ed1-9e71-0d75b25c6c57.png)

**Expected behavior**
No error message

**Comment by aerugo** [comment]
@alinauroz - we need to keep the modal open and add a red error message above the save button if the username is taken
