### ISSUE TITLE
[BUG] Refreshing breaks buckets table view sorting

### ISSUE THREAD

**Issue by DavidsBees** [cobudget/cobudget#1024]
**Describe the bug**
Submitted by user:

Open the main view which lists all the buckets for a project (or whatever is the correct terminology, in Borderland it would be the list of all dreams).

Steps to reproduce:
* view all buckets
* choose "table"-view
* sort by something (for example "Needed")
* refresh the page
* scroll down to load paginated results

It seems to use logic from the "grid"-view to load paginated results.
Instead of showing all the results in the same table, every paginated batch of items is presented as a separate table.

**Comment by aerugo** [comment]
This seems to no longer be an issue.

**Comment by aerugo** [comment]
I was able to reproduce with instructions above. 

<img width="1464" alt="Screenshot 2023-07-04 at 14 21 00" src="https://github.com/cobudget/cobudget/assets/7785081/d4fd539f-1d11-421d-b494-771ec39808db">
