### ISSUE TITLE
Updating packages in cobudget-api to newest version

### ISSUE THREAD

**Issue by jessykate** [cobudget/cobudget#113]

**Comment by jessykate** [comment]
@chime-mu is this ticket still active, or should we pull it off until it's more relevant/motivated?

**Comment by chime-mu** [comment]
@jessykate I'd like to think it's still active as I have a lot up unmerged changes, but I am focusing on #115 right now, so let's keep it here for this sprint and see how much time I have to actually work on it. Things should be slightly easier as I now can test stuff on the AWS deploy (and solve the Heroku deploy later)

**Comment by chime-mu** [comment]
Finally managed to find the problem with pushing this to Heroku. I now have a version with newer Gems on stage - still need to test with most recent frontend.

**Comment by jlopker** [comment]
@chime-mu this has been deployed, right? let's move to "done" if so!!
