### ISSUE TITLE
Dig into why the site is so damn slow

### ISSUE THREAD

**Issue by jessykate** [cobudget/cobudget#115]
also from [this doc](https://docs.google.com/document/d/1GpmNAXAA0XYx-QtgGXNeWhkMTK99Hhr1Uvnk2M9usuA/edit) there are the following notes:

```
How to fix Page Load
  * Group page has too much information
  * Cache group page and don’t hit up each time
  * Possible ui fix is to load page and then do 
  partial load on the content
```

**Comment by jessykate** [comment]
Also, FYI:
![screen_shot_2017-02-28_at_5 24 57_pm](https://cloud.githubusercontent.com/assets/59882/24156842/fec77796-0e57-11e7-8968-11125c4c14ba.png)

**Comment by chime-mu** [comment]
![skaermbillede 2017-04-01 kl 21 48 42](https://cloud.githubusercontent.com/assets/6072604/24581918/1d169c7e-1725-11e7-88f8-b203a5009e3f.png)

As measured from Denmark.

I suspect the backend is slow, although part of the apparent delay might be due to network delay form Heroku main site and Denmark. But average delays at 400-500 ms for backend call seems *very* slow. We do nothing complicated here, so I would expect sub 100 ms responses and then maybe 100 ms network delay, so max 200 ms.

Every time we show the group overview page we make 3 calls: 
* `groups`
* `buckets`
* `contributions`

The fact we do 3 calls is less than optimal (especially as each take 400-500 ms), but the `buckets` call is by far the worst as you can see. I've seen it last > 7000ms.

**Comment by chime-mu** [comment]
![skaermbillede 2017-04-01 kl 22 01 56](https://cloud.githubusercontent.com/assets/6072604/24582016/e35ac79c-1726-11e7-863a-3f58e0eaace2.png)

The frontend doesn't perform all that well as seen from above flamechart, approx 900 ms when'd displaying the group page from Enspiral. However compared to the backend delays I would say this is not where to focus at present. Besides Angular 1 is known to be slow, so if we want to optimise the frontend, we might want to look at newer virtual DOM based frameworks.

For now I think focusing on the backend is the way to go. The first step could be measuring DB read access times.

**Comment by chime-mu** [comment]
One more point. If I move from the group page to a specific bucket - and go back using the browser back button, we call the server all over again. 

I would say this is correct behaviour because I or other users might have changed stuff in the meantime, however

**Comment by chime-mu** [comment]
I've started instances on AWS that costs approx. the same as our current Heroku cost. I'll try to deploy  the version from the current `master` branch and run some tests. This is just to see if hardware makes a huge difference.

**Comment by jessykate** [comment]
Cool, that's great @chime-mu! Great digging!! Sounds like we should do some query analysis. I'd be surprised if the hardware made that big a difference but it's a good excuse to test out the AWS hardware in general as an alternative to heroku :).

**Comment by chime-mu** [comment]
Thanks @jessykate - I agree on the excuse part (and glad you like it ;-)
Also, yes to query analysis. I'm kind of baffled about this and hoping adding a simple index or two will do the trick.
@derekrazo - any thoughts on query performance or the general sense of cobudget being slow?

**Comment by chime-mu** [comment]
![pasted image at 2017_04_02 11_33 pm](https://cloud.githubusercontent.com/assets/6072604/24600141/8c344514-1853-11e7-8571-9e1629d8270b.png)

Problem description from Fran:

There's a speed issue when
* I switch between the tabs "all buckets", "funders", "stats"
* when for instance I start creating a new bucket and then decide to exit again (clicking the upper right hand corner)

and in general always when you click the x in the right hand corner to go back
that is pretty much it for what I can find for now!
but those 2 things really drive me nuts in everyday usage!
and I noticed by the way that the loading time for the tab "funders" is shorter if there are fewer people added
so it seems to be related partly to the amount of users in the group

**Comment by chime-mu** [comment]
![skaermbillede 2017-04-03 kl 12 57 39](https://cloud.githubusercontent.com/assets/6072604/24606387/3ac1f112-186d-11e7-85ab-20257238b4ec.png)

I did one more analysis based on Fran's feedback. The "start creating new bucket" use case is again pointing to the group overview page and the `buckets`call.

The "switch between tabs" use case is dependent on the `membership` call, which takes > 5000 ms, so we should look at both `buckets` and `membership`

**Comment by chime-mu** [comment]
![skaermbillede 2017-04-04 kl 23 48 18](https://cloud.githubusercontent.com/assets/6072604/24680462/50242686-1991-11e7-8355-052e51ba80f2.png)

I have the backend server running on AWS. As seen from above, this cuts the execution times approx in half, which is good, but still way too slow. So we need to look at what actually takes time.

Current hypotheses:
1. Database queries
2. In the case of buckets, 3 get requests is sent at the same time. It seems the `buckets` request always wait for the others - so potentially the threading solution isn't really working. Not sure though.

**Comment by jessykate** [comment]
@chime-mu interesting! is this equivalent hardware? if not what is the difference?

**Comment by chime-mu** [comment]
No, this is probably significantly more potent hardware both for DB server and app server. Hard to say exactly what the difference is as we don't run on dedicated Virtual servers on Heroku, but on containers. The HW on AWS is in the same price-range as our current Heroku price (approx 10% more expensive), so I expect more power.

**Comment by jlopker** [comment]
these are very interesting findings @chime-mu! nice work. i'm happy to have you keep running with this but am also available to help if you'd like. is there anything that you could you assistance on?

**Comment by chime-mu** [comment]
[Cobuget SQL dump.txt](https://github.com/cobudget/cobudget/files/894685/Cobuget.SQL.dump.txt)

Found the problem. It's not a single query that's the problem. It's the fact that the `budgets` API, issues approx 700 SQL statements!

**Comment by jlopker** [comment]
note to self: look into only showing the spinner if the site is taking more than 500ms to load

**Comment by chime-mu** [comment]
There's already done a lot of work in this ticket and given the title "Dig into why the site is so damn slow", we could choose to say we've identified some of the main reasons. So we could choose to create tickets to make the changes and the close this one. For example:
- As a user I have a fast pageload of the bucket page so I feel the site is easy to use (fast < 500ms, 95%)
- As a user I have a fast page load of funders page so I feel the site is easy to use
- As a user I see a spinner when the site is slow, so I understand I'm waiting for the site, not the other way around. (slow > 500ms)

What do you think @jlopker ?

**Comment by chime-mu** [comment]
This SQL query gives all the information in the list of buckets:

SELECT status, name, target, funding.total, funding.user, com.count
FROM buckets
LEFT JOIN (SELECT bucket_id, sum(amount) as total, 
                  sum(CASE WHEN contributions.user_id = 2695 THEN amount ELSE 0 END) as user
           FROM contributions GROUP BY bucket_id) AS funding ON buckets.id = funding.bucket_id
LEFT JOIN (SELECT bucket_id, count(*) FROM comments GROUP BY bucket_id) AS com on buckets.id = com.bucket_id;

It executes in 327 ms on the Heroku database and in 6 ms (!) on the AWS database. 

Both are significantly faster than the current query time and clearly this scales better.

**Comment by jessykate** [comment]
that sounds clear to me @chime-mu. i guess whether we use this ticket or another, there's some clear action items around optimizing the queries.  

if you or @jlopker think you can implement these improvements during this sprint, then i would propose we can keep this ticket but flesh it out with the specific actions you identified. otherwise let's mark this ticket as done and scope out one or more new tickets for the implementation. 

as i'll be away next week can i leave it to one of you to own the workflow around this ticket either way? @chime-mu my sense was that @jlopker was happy to have you run with this, if you are up for that!

**Comment by jessykate** [comment]
Outcome - key speed-affecting issues:

1. github pages seems slow for serving the frontend
1. slow/unstrategic DB queries (buckets and memberships specifically) & some amount of query duplication/laziness. 

things to do:
1. move front end to own server? possibly to AWS 
1. which begs the question of moving the back end to AWS too
1. database query improvements

**Comment by jessykate** [comment]
marking this as closed since we have other tickets reflecting specific improvements now (moving to AWS, DB query optimizations)
