### ISSUE TITLE
Change payment tiers

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#1190]
We need super admins to be able to override the round limit manually. Add a "Super Admin" section to the round settings where we can input a new max number of participants for a round.

Also update the upgrade prompt to have this text:

"Group subscription has expired. To continue using the group, please upgrade your subscription. Groups can have up to 1000 participants per round, and an unlimited number of rounds. For even larger rounds, <a href="mailto:hello@cobudget.com?subject=Custom size round">get in touch</a>. "

**Comment by francesca-sp** [comment]
From what I can test, it looks good. The only thing is that I don't have a list of 1000+ handy, to test if it actually works, but I guess you have done that with the borderland? 

Language-wise, I would suggest an edit. It seems like it could be confusing to read "subscription expired", if you never had a subscription. Also, is it an error that it says group, shouldn't it be round? Secondly, I would like to include a note for people to get in touch to discuss non profit plans. 

New text proposal: 
"You need an active group subscription to continue using this round(??). Please upgrade. Groups can have up to 1000 participants per round, and an unlimited number of rounds. For larger rounds and non-profit discounts, [get in touch](mailto:hello@cobudget.com?subject=Custom%20size%20round).

**Comment by francesca-sp** [comment]
Now, when I try to invite more members than the limit, instead of the subscription text, I get this error message: 

![image](https://github.com/cobudget/cobudget/assets/3641828/cd0ce842-f6c5-4f53-90ef-eafb079f2c2c)

**Comment by francesca-sp** [comment]
And i am now getting a graphql error here: 
![image](https://github.com/cobudget/cobudget/assets/3641828/13ddf6a7-c998-4590-aba3-c95078a34cc4)

**Comment by alinauroz** [comment]
> Now, when I try to invite more members than the limit, instead of the subscription prompt, I get this error message:
> 
> ![image](https://private-user-images.githubusercontent.com/3641828/298516240-cd0ce842-f6c5-4f53-90ef-eafb079f2c2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MTY5ODYsIm5iZiI6MTcwNTkxNjY4NiwicGF0aCI6Ii8zNjQxODI4LzI5ODUxNjI0MC1jZDBjZTg0Mi1mNmM1LTRmNTMtOTBlZi1lYWZiMDc5ZjJjMmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMDk0NDQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmUwZGE3NzkwMmUxZGI5ZmMyNzVmZjdmMGFkODBjMDc3NDg3MmY1NmI2NDJjZDQ2NjJlOWFiYmJlYmZlMzQ5NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Atw4Jqu4NDAVhK5BUmhhdoLMPbe8IFvrQgnTzQGHsRo)

This is a general message. It will be shown to the paid rounds if they exceed the round member limit. I can do this:
1. If a round is not paid, we show them subscription text
2. If a round is paid, and they have reached the limit, we ask them to contact support.
