### ISSUE TITLE
As a member of Cobudget team, i'd like to see meaningful analytics

### ISSUE THREAD

**Issue by jlopker** [cobudget/cobudget#148]
from kate (for /analytics): 

Can we please filter by member count (8 or above - this this can be confirmed or unconfirmed members)

And add data on:
Total money that the group has moved through the tool
Total number of buckets funded

**Comment by jlopker** [comment]
in branch `hotfix/super-admin-data`

**Comment by jessykate** [comment]
merged!

**Comment by jlopker** [comment]
@jessykate this still needs to be deployed
