### ISSUE TITLE
As a user, it's not obvious enough that I can add funds via the funders tab

### ISSUE THREAD

**Issue by jlopker** [cobudget/cobudget#150]

**Comment by jlopker** [comment]
<img width="740" alt="screen shot 2017-05-01 at 2 49 03 pm" src="https://cloud.githubusercontent.com/assets/3010270/25596369/a5e9606c-2e7d-11e7-8735-9edb35a14064.png">

**Comment by jlopker** [comment]
options 2: new plus button

<img width="685" alt="screen shot 2017-05-01 at 3 09 49 pm" src="https://cloud.githubusercontent.com/assets/3010270/25596860/47123c28-2e80-11e7-9ddf-4fc6740a0fd3.png">

**Comment by chime-mu** [comment]
Thanks for the proposals @jlopker.

Personally I like both of them but with a slight preference for the "+" button.

From my own experience on using cobudget, I see the larger problem being the "manage funds" button. My assumption would be that all functionality around managing funds is visible through clicking on that button. So I simply never look in the "Funders" tab.

I think it's confusing we can add fund two different places. I have no clear idea about how to solve it, I just believe we need to work on a solution that includes having all manage-fund functionality in the same place.

What do you think? Does this make sense to you?
