### ISSUE TITLE
SSL Cert has expired on cobudget.co

### ISSUE THREAD

**Issue by BenGalewsky** [cobudget/cobudget#169]
# Problem
When I visit `https://cobudget.co` I see an error about the SSL cert. Safari says that the cert expired.

# Log Files
I see this problem in Safari and Chrome. Chrome provides this detailed error report:
```
This server could not prove that it is cobudget.co; its security certificate expired 3 days ago. This may be caused by a misconfiguration or an attacker intercepting your connection. Your computer's clock is currently set to Monday, March 11, 2019. Does that look right? If not, you should correct your system's clock and then refresh this page.
```

**Comment by chime-mu** [comment]
Hey @BenGalewsky - thanks for reporting. I'm on it.

**Comment by chime-mu** [comment]
Should be solved now
@BenGalewsky
