### ISSUE TITLE
[FEATURE] UI translation

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#213]
We need to implement localization of the frontend client. 
Because of overlapping communities, we would like to use the same approach as [OpenCollective](https://github.com/opencollective/opencollective-frontend) which uses [crowdin.com](https://crowdin.com/project/opencollective). 

Implementing localization will be done in steps:

- [x] Set up a project on Crowdin (https://crwd.in/cobudget)
- [x] Check with @znarf of OpenCollective if they are planning to stick with Crowdin. Done: They are happy with it and recommend it.
- [x] Research Crowdin, the OpenCollective implementation, and devise a plan for implementing Crowdin in Cobudget
- [x] Research what needs to be done to enable support for localization in RTL languages with Crowdin
- [x] Replace all hardcoded strings with localization library variables
- [x] Implement the first partial translation of a single page into Swedish
- [x] Test RTL support by implementing a partial Arabic translation of a single page

**Comment by aerugo** [comment]
Closed in issue clean-up.

**Comment by skoteskote** [comment]
I can produce the translated text files, just let me know how I should structure them.

**Comment by skoteskote** [comment]
I would like to prioritize this issue so it is done by the summer, when I will start to reach out to orgs as a part of the Kulturbryggan project.

**Comment by Powersource** [comment]
This is on staging now

**Comment by francesca-sp** [comment]
Could you say more about what needs to be tested here from our side @Powersource ?
