### ISSUE TITLE
Limit collection homepage text length - Make sure titles of dreams are visible in collection view

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#271]
The purpose of the collection view is to see the collection of dreams. The current layout easily leads to dreams not being visible due to long homepage texts. On my 13th inch screen, it's only [Tau Tools and Upgrades](https://dreams.blivande.com/tau-tools-and-upgrades) of Blivande's collections that have dream titles visible immediately. This is quite important from a UX perspective, people need to get what the page is about and not have to scroll to be enticed by all the juicy content. 

Potential solutions that can be combined in various ways: 
* Limit homepage text length. We probably want to do this anyhow. People don't really seem to know what the homepage text is. It should ideally be like 2-3 sentences of pepp and info on where to get more information.
* Reduce space around homepage message (ideally not, it's great as it is.)
* Move the collection menu to the top right corner, or some other location. I understand the current placement is due to what level in the hierarchy you are on, but there could be solutions to clarify this with the menu in a different location too. 

Example of not visible dreams:
<img width="1372" alt="Screenshot 2021-06-07 at 18 04 18" src="https://user-images.githubusercontent.com/11414586/121053938-28f73200-c7bc-11eb-9193-41812fc39d47.png">

**Comment by Powersource** [comment]
How about we do like we had it before, it's short by default but you can click the bottom of it to expand it?

**Comment by Powersource** [comment]
We added a limit on the length for the new org homepage text, so could just copy that logic. The harder part is figuring out what to do about the collections with already existing long texts

**Comment by aerugo** [comment]
I no longer this this is a priority. Feel free to reopen if you disagree.

**Comment by skoteskote** [comment]
Hmm, I don't think we ever added that limit? There is currently no text limit on a round's home page description. Technically it can look like this (which is pretty bad IMO). Maybe not priority but defo something we wanna look into eventually, for example in the Engaging bucket & Collection Display milestone.
<img width="1604" alt="Screenshot 2022-03-13 at 18 28 45" src="https://user-images.githubusercontent.com/11414586/158071762-5b2479e8-858f-4a91-8f42-bd5625b552b5.png">

**Comment by aerugo** [comment]
We never added it, but I am not sure we should. This is also nothing that has been discussed with the new team. If we still want a limit, it should be discussed, them reopened if it is desired.
