### ISSUE TITLE
[FEATURE] Shuffle dreams also for users that are not org members

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#297]
followup from https://github.com/Edgeryders-Participio/multi-dreams/issues/278

The user's seed is derived from their orgMember.createdAt, so if they're not a member of that org they get the same shuffle as logged out people.

**Comment by Powersource** [comment]
Waiting until https://github.com/Edgeryders-Participio/multi-dreams/pull/300 is merged

**Comment by gustavlrsn** [comment]
This is already fixed, seed is based on todays date abd user id if it exists:
```js
const todaySeed = dayjs().format("YYYY-MM-DD");

const shuffledBuckets = SeededShuffle.shuffle(
    buckets,
    user ? user.id + todaySeed : todaySeed
);
```

**Comment by Powersource** [comment]
This can turn into a bug if the user keeps the page open past midnight but that's maybe fine for now
