### ISSUE TITLE
[FEATURE] Add sortable table in collection page

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#306]
People should be able to switch from the still default grid layout to a table.

`limit` should probably be a lot higher or uncapped

Inspo

![image](https://user-images.githubusercontent.com/1427063/123607248-fca06580-d7fd-11eb-9448-f8c0311f2096.png)

**Comment by aerugo** [comment]
@Diemo-zz this will probably be useful to you, and we hope to have it ready before too long.

**Comment by DiarmaidEverycs** [comment]
That would be great.

**Comment by aerugo** [comment]
Table should show all buckets in the round.

Columns:
 - Name
 - Minimum budget goal
 - If stretch goals enabled for round: Maximum budget goal
 - Existing funding (not through cobudget)
 - Funds given through cobudget
 - (%) of minimum goal reach
 -  If stretch goals enabled for round: (%) of minimum goal reach
 - Number of "Everything looks fine" flags
 - Number of review flag toggles

**Comment by aerugo** [comment]
We now want to merge this into Cobudget prod - @gustavlrsn

**Comment by francesca-sp** [comment]
Where exactly can we test this feature? Looking through staging, I don't see it anywhere. Is this on a different instance? @aerugo

**Comment by tomomiq** [comment]
Requests: 

* If reviews are not turned on, hide the Approvals and Flags column 
* Add a column: Date created 
* Add a column: Status 
* Rename column: Title → Bucket 
* Rename column: Resources → Existing funds 
* Column order: Title, Status, Goal, Funded, Resources, Needed, Progress, Funders, Approvals, Flags, Date created 
* Add up/down arrows next to the column labels, so the user knows they can re-order
