### ISSUE TITLE
Move to  Passport and Prisma

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#320]
## Goals:
1. Replace Keycloak with Next-auth
2. Replace mongoDB with Postgres and Prisma

## Motivations:
As the project is growing in size and complexity, some technical debt is showing. 

We chose Keycloak with the idea that it would help us do OIDC auth easily, to allow other organizations to use their own auth. However, it has proven to take a lot of energy to work around the quirks of using Keycloak, it mostly comes down to putting our entire auth thing in another entity, separate from the main project, both in terms of data and in terms of UI. Fixing small things that should be easy is difficult.

Using [NextAuth](https://next-auth.js.org/getting-started/introduction), a well proven auth library for Next.js that I've used many times, we can put all our UI into the same application, and all our user data in the same database. It [does not have explicit built-in OIDC support yet](https://github.com/nextauthjs/next-auth/issues/250), but it's easy to add a auth provider to it, and there are several provider configurations that are implemented against an OIDC service that we can use to implement new providers (such as Borderland auth etc).

MongoDB is brittle, we've had several instances where data is missing for one reason or the other. It also has no built in support of migrations and changes to the data model. 

As we only deal with relational data, it makes no sense to use MongoDB. PostgreSQL is a proven technology and it works.

On top of Postgres I suggest we use Prisma. Prisma gives us declarative data modeling and a built in migration system, as well as a type-safe query builder.

I've used this recently in a couple of projects and it makes working with the data layer a joy.

### Step 1: Replace keycloak and mongodb (2 weeks)

- [x] Define a new prisma schema for the whole project, including models for next-auth
- [x] Replace calls to Mongoose and Keycloak with calls to Prisma

### Step 2: Migrate (1 week)

- [ ] Migrate all existing dreams data from keycloak and mongodb to postgres

**Comment by aerugo** [comment]
Good plan.

> It does not have explicit built-in OIDC support yet, but it's easy to add a auth provider to it, and there are several provider configurations that are implemented against an OIDC service that we can use to implement new providers (such as Borderland auth etc).

I am not completely sure what you mean here. 
Will it be reasonably easy to add a feature that lets us configure an org to auth with a different auth provider than other orgs?
What would such "provider configurations" be? Does it actually mean that we would need to connect the Borderland org to something like an Auth0 org for the Borderland which then connects to the Borderland Keycloak?

**Comment by gustavlrsn** [comment]
> Will it be reasonably easy to add a feature that lets us configure an org to auth with a different auth provider than other orgs?

Yeah, this should be easy to do.

> What would such "provider configurations" be? Does it actually mean that we would need to connect the Borderland org to something like an Auth0 org for the Borderland which then connects to the Borderland Keycloak?

No, we should be able to connect directly to the Borderland keycloak by adding a provider configuration for it, that looks something like this: https://next-auth.js.org/configuration/providers#using-a-custom-provider

**Comment by gustavlrsn** [comment]
Closing this, just the migrate step left but #414 tracks that
