### ISSUE TITLE
Switch to a wysiwyg text editor

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#339]
Because people don't get markdown

This one looks decent https://github.com/nhn/tui.editor (you have to click the markdown button in the bottom right of the editor in the demo)

* For comments https://github.com/cobudget/cobudget/pull/360
* For the rest https://github.com/cobudget/cobudget/pull/502

**Comment by aerugo** [comment]
I get an error when I try to edit comments with the new editor:
https://cobudget.com/c/burberland/ckxbdjk7k077509l1mdweqf9o
<img width="1792" alt="Screenshot 2022-01-14 at 02 18 28" src="https://user-images.githubusercontent.com/7785081/149434619-8355f614-b691-4d36-bdbc-bd8e132cb4ff.png">

**Comment by Powersource** [comment]
:tada:
