### ISSUE TITLE
Move the Funders list in the Bucket page to a tab

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#348]
![Image 2021-10-05 at 3 45 35 PM](https://user-images.githubusercontent.com/1287179/136040160-4e3dd939-f81a-4a3b-b347-67918d351c25.jpg)

This one's a combination of a few things... 

- Move the Funders list to Tabbed view so there's more space for longer lists 
- Specific order for the list 
- Add simple pie chart visualization 
- Mask e-mail addresses for security reasons

**Comment by tomomiq** [comment]
Moving this to be included in the transition release. 
Let's deprioritize the pie chart element but get this list done.

**Comment by gustavlrsn** [comment]
I'm wondering if we should use the tab sub menu component from collections and orgs, to harmonize tabs and pages across the platform

**Comment by gustavlrsn** [comment]
![image](https://user-images.githubusercontent.com/1552194/148288325-7e55e96f-133b-47d6-a7df-c7a8f184068c.png)

**Comment by gustavlrsn** [comment]
ping @tomomiq

**Comment by gustavlrsn** [comment]
Maybe something like the way Kickstarter does it would be nice, keep some essentias above the tab menu, but not the entire campaign:
![image](https://user-images.githubusercontent.com/1552194/148292890-ca97cd0e-b52d-4ae9-9861-ab06af2c98f8.png)

**Comment by tomomiq** [comment]
Yep, I think we can kill Overview (it'd just be the top half of the page) and then re-use the tab sub menu for Comments and Funders.

**Comment by gustavlrsn** [comment]
I'm thinking that the main bucket content would be a tab as well? Maybe even budget since its a bit special 🤔

**Comment by aerugo** [comment]
As long as the description is on the first tab you see, I'm all good with that. But let's not hide the budget in a separate tab. We are called Cobudget, after all - it would be weird if he hid the budget.

**Comment by gustavlrsn** [comment]
Makes sense

**Comment by gustavlrsn** [comment]
Merged the thing in #503
