### ISSUE TITLE
Only admins and guides should be able to create new tags and delete them

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#351]
But anyone should be able to use them

* [x] https://github.com/cobudget/cobudget/pull/357
* [x] https://github.com/cobudget/cobudget/pull/477

**Comment by aerugo** [comment]
Not for now, I think. I think that in use cases where this is important, there will probably be enough trust involved that people who want to add tags can be made guides. But most of the time, the tagging free-for-all is a bad idea, as demonstrated by Kiezburn:

<img width="1980" alt="Screenshot 2021-10-15 at 14 41 04" src="https://user-images.githubusercontent.com/7785081/137488369-092f354d-37e9-4e42-b5c4-64e34b4b226b.png">

**Comment by Powersource** [comment]
pr still unmerged

**Comment by aerugo** [comment]
We will keep this open until there is a way to delete tags.

**Comment by aerugo** [comment]
@Powersource - nothing happens when I try to create tags in production.

**Comment by Powersource** [comment]
huuh same for me in production, but still works in dev, so annoying. will check logs

**Comment by aerugo** [comment]
Gotcha! Let’s check if things work in production from now on before closing
issues.

**Comment by Powersource** [comment]
we have github set to autoclose issues once PRs are merged, i'll see if i can disable that

**Comment by Powersource** [comment]
doesn't sound [like we can disable it](https://github.community/t/feature-request-prevent-issues-from-being-closed-by-merging-linked-prs/3255), but we can avoid using the auto-closing keywords

**Comment by gustavlrsn** [comment]
Creating tags work for me, can you test again @aerugo?

**Comment by gustavlrsn** [comment]
Closing this, reopen if you still have issues. Might have been the deploy that didn't go through for some reason.

**Comment by aerugo** [comment]
Confirmed, it works now.
