### ISSUE TITLE
[FEATURE] Show bucket status clearly on bucket page

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#371]
As a user, I want to clearly see which part of the "life-cycle" a bucket is in when I am viewing the bucket.

**Comment by francesca-sp** [comment]
There is feedback in #385 about the design and copy of this, which applies the same for this issue. This needs to be incorporated before it can be pushed live.

**Comment by tomomiq** [comment]
Still waiting for labels to have the right colors :)

**Comment by aerugo** [comment]
Closing this one and moving colors to new issue https://github.com/cobudget/cobudget/issues/814
