### ISSUE TITLE
Filter buckets on status in collection

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#384]
As a user, I want to filter the buckets in a collection by where they are in the bucket "life cycle".

**Comment by gustavlrsn** [comment]
@aerugo @tomomiq Are these the states we aim to cover with the filter?
- Open for funding
- Pending admin approval
- Funding will open on <date>
- Delivered/completed
- Archived
- Funding closed

Taken from https://whimsical.com/funding-status-SdCAS8xZc5nXcVJjcRh9Pp

**Comment by tomomiq** [comment]
Worked on with Gustav in our co-design session! 

<img width="759" alt="Screenshot 2022-01-25 at 15 28 22" src="https://user-images.githubusercontent.com/1287179/150995560-79311a65-7ead-4dab-a7b7-d4b191c5ec64.png">
