### ISSUE TITLE
[FEATURE] Show bucket status on bucket card

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#385]
As a user, I want to see where in the "life cycle" a bucket is on the bucket "card" in its collection.

**Comment by DavidsBees** [comment]
Feature is working - labels are visible in the overview on top of cards.

In our testing session today we thought it would be good to change the taxonomy for more clarity. Here is what we would propose (ideally each in a different colored label):

Unpublished (grey) - triggered once a bucket is created but not published
Idea Stage (yellow) - triggered once a bucket is published
Pending approval (red) - triggered when co-creator wants to open for funding and settings set to "moderator approval needed"
Open For Funding (orange) - triggered when Co-Creator accepts funding
Funding closed (purple) - triggered when bucket fully funded or "funding accepted"
Completed (green) - triggered when hit "mark as completed"

**Comment by aerugo** [comment]
@alinauroz please update the label texts to what @DavidsBees suggested

**Comment by tomomiq** [comment]
hi @alinauroz this has been tagged as "needs testing" but we don't see colored labels on staging. passing back to you!

**Comment by aerugo** [comment]
I have closed this one and created https://github.com/cobudget/cobudget/issues/814
