### ISSUE TITLE
[FEATURE] Sort buckets in collection on percentage funded

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#386]
As a user, I want to be able to sort buckets in a collection by how close they are to being fully funded.

**Comment by tomomiq** [comment]
Something like that? 

<img width="841" alt="Screenshot 2022-06-23 at 08 31 37" src="https://user-images.githubusercontent.com/1287179/175230859-a696b025-2f62-4b79-8a3b-63d92d739c49.png">

**Comment by francesca-sp** [comment]
It seems that what has been implemented is totally different from @tomomiq's mockup above. Is there a reason for this? 
I really prefer the language used in her mockup, it seems more clear and more common in terms of what people will be used to from other apps. 

![image](https://user-images.githubusercontent.com/3641828/178234460-13575189-9303-43f4-ade0-f5529ec597ef.png)

**Comment by aerugo** [comment]
@alinauroz - could you fix it to be identical to the mockup?

**Comment by francesca-sp** [comment]
How complicated is it to store those numbers (transactions + comments) in the database do you think? @aerugo 

We would suggest to decide on whether its worth building this as well, or otherwise go with the pragmatic option, and simply implement the mockup with only 2 options instead: 
* Newest
* Most funded (%)

**Comment by aerugo** [comment]
@alinauroz

Let's do it this way.

Sorting options are:
- Random
- Newest
- Most funded
- Most contributions

Random is the default option.

Add number of contributions to the database to enable sorting on that property. 

@tomomiq - I like the idea of "Most active" but I think it will be a little unclear for the user what they are actually sorting on. I think that we should generally avoid showing these sorts of aggregate metrics. Furthermore, there is a slight technical problem with this that only affects the Blivande instance at the moment, which is that when we use Discourse as a comment engine we need to make a call to Discourse for each bucket to get the number of comments.  This means that we would need to build a special case where the "Most active" is hidden if Discourse implementation is enabled.
