### ISSUE TITLE
Admin invites members to group by email from contributors page.

### ISSUE THREAD

**Issue by derekrazo** [cobudget/cobudget#39]
This ticket includes a simple design of the members page, as well as a post to the api, and implementation on the ui.

Requirements:

- emails user invite

**Comment by derekrazo** [comment]
Members are only people who have accepted their invitations.

People get invited even if they already have a cobudget account.

**Comment by derekrazo** [comment]
potential first solution is to send an email with user account created and password being password.

**Comment by jonlemmon** [comment]
Please note, these mockups are not exact... just use the existing bootstrap styling that we already have for this stuff.

1. Clicking "Add Contributor" makes the dropdown appear. Clicking the "+" at the top of the list also makes the same dropdown appear. Only one dropdown should ever be visible at a time on the app

![1 add contributor](https://cloud.githubusercontent.com/assets/1179717/5952930/e4dc2a6e-a7e5-11e4-9db2-51c9a13d370d.png)

2. Here's a draft of what the email invitation could look like. I stuck with plain text for now. The link will be to the round that you were on when you added the contributor.

![2 email invitation to round](https://cloud.githubusercontent.com/assets/1179717/5952931/e4e62f1e-a7e5-11e4-8623-32cb92ad8d43.png)

3. Once you've clicked the link, it will take you to the round with the following banner at the top of the page. This banner will stick to the top no matter what page you are on (until you click the 'x'). If you click the 'x' you will no longer see the banner unless you visit the invitation link again).

![3 invitation banner](https://cloud.githubusercontent.com/assets/1179717/5952932/e4e9b2ce-a7e5-11e4-8efd-d0f7905fee1d.png)

4. If you're logged in, clicking "Join" will add you to the group and take you back to the round. If you're not logged in, it will pop up this "Create account or log in" modal. After creating an account or logging in, you will be taken back to the round.

![4 create account or log in](https://cloud.githubusercontent.com/assets/1179717/5952933/e4ed4646-a7e5-11e4-84ba-989036cf2d31.png)

**Comment by derekrazo** [comment]
Checked in feb 3 - @jonlemmon  to update with feedback on invitation system. "include invitation token on every token."
