### ISSUE TITLE
Implement email notifications for events according to specifications

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#393]
As an organization admin, I want certain events to trigger notification emails. This issue also involves defining what those events are.

* [x] Invite_email (Join by invitation)
* [x] Confirm_account_email (Join by signing up yourself)
* [x] Welcome Email (after accepted invitation and after confirming email on self-sign-up) (only need to update text now)
* [x] ~Reset_password_email~ we don't have passwords (yet)
* [x] Notify_member_new_comment_in_bucket
* [x] Notify_member_new_comment_to_comment
* [x] Notify_member_that_they_received_allocation
* [x] Notify_funder_that_bucket_was_cancelled
* [x] Notify_member_new_funds_in_bucket (cocreator rather than member i guess) (do we actually want this every time? yes we'll do this for now)
* [x] Notify_member_new_bucket_in_group

**Comment by tomomiq** [comment]
Links: 

Flows and triggers 
https://whimsical.com/emails-8up4tNoUDT2ubjNNm6xfXi

Template text 
https://docs.google.com/document/d/1O5ZAVGcye9gOI9RZrvDs0Vs9DgRRF23bHxnfVpflwUs/edit

**Comment by Powersource** [comment]
@tomomiq in that first link, "prioritized" is "prioritized implementation" or?

**Comment by tomomiq** [comment]
Yes. 
(And in Spain we agreed with Hugi that the Digests would be de-prioritized, so I changed that from red to grey just now.)

**Comment by Powersource** [comment]
@tomomiq I've tried to combine the emails from the two links and made a list up top here, keeping only the prioritized ones. Can you check that it looks correct? Only one I'm unsure of is what the "New bucket online" in the graph means, I didn't include that one here now.

**Comment by Powersource** [comment]
and what's our idea for "As a user, I want to be able to toggle which events lead to notification emails.", do we skip this initially? do i add a simple settings page with a checkbox for all of the above types?

**Comment by aerugo** [comment]
A simple settings page is the right way to go. It should be reasonably easy
to implement a page with some toggles?

**Comment by Powersource** [comment]
Well yes, but we also have like 3 weeks (if discounting holidays) until the milestone should be done 😅

**Comment by aerugo** [comment]
Yeah, true. Leave the setting toggles for now, but make another issue for
them and push it to the next milestone.

**Comment by DavidsBees** [comment]
@Powersource The list is looking good and covers all. "New Bucket online" refers to the trigger through a new bucket in a group you are a member in. I added it now in the doc. True that for the last one (new funds) its the co-creators receiving that notification.

**Comment by gustavlrsn** [comment]
Closing, merged in #485
