### ISSUE TITLE
Design notification email

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#394]
As an organization admin, I want notification emails to be well designed so that they bring attention to the thing that is intended with the notification.

**Comment by Powersource** [comment]
the email text has been defined in here https://docs.google.com/document/d/1O5ZAVGcye9gOI9RZrvDs0Vs9DgRRF23bHxnfVpflwUs/edit?usp=sharing

**Comment by Powersource** [comment]
although not all of those notification emails need to be finished by dec 1st right, i think we said end of year?

**Comment by tomomiq** [comment]
Assigning to myself to propose a simple template design, just a bit of branding and some guidelines for common elements

**Comment by Powersource** [comment]
I'll move this away from this milestone. We'll get emails with very basic html in https://github.com/cobudget/cobudget/pull/485 but fancy html and css is gonna be a bigger effort.

**Comment by aerugo** [comment]
I am closing this, and we may open a "fancy HTML emails" issue in the future.
