### ISSUE TITLE
[FEATURE] Org can subscribe to CoBudget paid plan

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#395]
As Cobudget, we want certain features to be limited to paid plans, and we want those to be enabled automatically when a user signs up for a paid plan with their organization. 

* [ ] Maybe add a tax_rate when checking out?

**Comment by Powersource** [comment]
Note to testers: this is done, except that maybe we want to add a tax rate on checkout (i guess makes it easier for us on the stripe side)

**Comment by gustavlrsn** [comment]
There was an issue with the Stripe webhook setup, fixed now, so group creation should work. Although you will be redirected to the group homepage and not the setup page currently.
