### ISSUE TITLE
[FEATURE] Org setting page to control org plan

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#397]
As an org owner, I want to be able to control by subscription to a paid Cobudget plan through the org settings menu.

**Comment by tomomiq** [comment]
Related: I mocked up a structure for group-level settings pages as part of the "donate to group" feature, placing the subscription page here → 

<img width="528" alt="Screenshot 2022-06-23 at 09 00 29" src="https://user-images.githubusercontent.com/1287179/175236235-92953a6e-a2f2-47fb-b8f0-bebbc05534f6.png">
