### ISSUE TITLE
Migrate all of the groups and buckets from the old cobudget

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#414]

**Comment by francesca-sp** [comment]
Putting the document here @gustavlrsn with my draft thoughts on the migration: https://docs.google.com/document/d/1R3JaOmlSCsh-OVLbdgljoHKAj5ghrzq1vh9lEnwbtlQ/edit

If you could add comments in there on elements that you think will be difficult or easy, that would be great!

**Comment by chime-gm** [comment]
I've started to work on the export of data from the old cobudget. To begin with I've looked at groups, buckets, users and comments. Looking at Frans plan, that should cover the current plan.

Let me start by sharing the current schemas.

## Groups

```
CREATE TABLE groups (
    id SERIAL PRIMARY KEY,
    name character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    currency_symbol character varying DEFAULT '$'::character varying,
    currency_code character varying DEFAULT 'USD'::character varying,
    customer_id character varying,
    trial_end timestamp without time zone,
    plan character varying,
    description text,
    funding_freeze boolean DEFAULT false,
    status_account_id integer REFERENCES accounts(id),
    add_funds character varying
);
```

## Buckets

```
CREATE TABLE buckets (
    id SERIAL PRIMARY KEY,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    name character varying,
    description text,
    user_id integer,
    target integer,
    group_id integer,
    status character varying DEFAULT 'draft'::character varying,
    funding_closes_at timestamp without time zone,
    funded_at timestamp without time zone,
    live_at timestamp without time zone,
    archived_at timestamp without time zone,
    paid_at timestamp without time zone,
    account_id integer REFERENCES accounts(id)
);
```

## Comments

```
CREATE TABLE comments (
    id SERIAL PRIMARY KEY,
    body text NOT NULL,
    user_id integer,
    bucket_id integer,
    created_at timestamp without time zone NOT NULL,
    updated_at timestamp without time zone NOT NULL
);
```

## Users

(removed some information about tokens and stats, not useful)

```
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    email character varying NOT NULL DEFAULT ''::character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    name character varying,
    utc_offset integer,
    is_super_admin boolean DEFAULT false
);
```

@gustavlrsn

**Comment by chime-gm** [comment]
As for export I propose either CSV or JSON. Both are fairly manageable options from this side.

For CSV I would export each table by itself.

For JSON, we can either export each table by itself or export buckets as an array in groups.

Have a look at all this @gustavlrsn and please share any questions.

**Comment by gustavlrsn** [comment]
@chime-gm some kind of JSON would be great. Buckets as an array in groups sounds good too!

**Comment by aerugo** [comment]
I have [written a script](https://github.com/cobudget/group-migration) now to export all relevant data from any group to  JSON. An example of (my own) group data here: https://github.com/cobudget/group-migration/blob/main/group_exports.example.json
