### ISSUE TITLE
User can switch between orgs

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#415]
next step: sketch a proposal

**Comment by aerugo** [comment]
Is this more or less already implemented now @tomomiq and @gustavlrsn?

**Comment by francesca-sp** [comment]
I've found 2 issues with the implementation of this switcher: 
1. I uploaded a square image as a logo for the Enspiral group, and the logo gets distorted in the group/round selector dropdown. It looks fine though when I am on the group main page (not inside a collection)

See screenshots: 
![image](https://user-images.githubusercontent.com/3641828/155587885-957dfd2f-d774-4f21-946f-33f376b34fff.png)
![image](https://user-images.githubusercontent.com/3641828/155588830-ca23223e-e1b1-4985-9aa7-863204a42a3f.png)

2. When clicking into a round inside a group, the Group name gets almost totally cut off and there are [...] instead. 
See screenshot: 
![image](https://user-images.githubusercontent.com/3641828/155588504-9e3ca02f-0f78-4824-b329-bb51f2e9ba52.png)

Browser: Chrome
Device: Windows

@Powersource do you prefer I create separate issues for these both, or can we discuss here?

**Comment by Powersource** [comment]
i would say create new issues for these and close this one

**Comment by francesca-sp** [comment]
@Powersource here is the new issue: https://github.com/cobudget/cobudget/issues/584
