### ISSUE TITLE
[IDEA] clean up the UX of create account - login - add username

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#416]
next step: sketch a proposal

**Comment by tomomiq** [comment]
And then the second part of the proposal is in regards to prompting the user to set a Username for the Group that they're joining. 

Design context: 
- As much as possible, we want to encourage the user to set a Username, to have a public-facing identifier that is not "Somebody" 
- User can state how they want to be identified within the context of each Group that they're in. It needs to be an opt-in process to honor people having multiple identities. 

Flow for user with an existing cobudget account 
1. User receives an invite e-mail to join a Group 
2. User clicks on link to accept invite 
3. User is taken to logged in Group top page, with a pop-up that asks them to set their Username for that particular Group. Prefilled text for the field: Name (which they can then edit)

Flow for user without an account 
1. User receives an invite e-mail to join a Group 
2. User clicks on link to accept invite 
3. User goes through account creation plus joining the Group and setting their Username as part of the same flow (← not entirely sure how this works, wasn't able to test on the new deployment)

**Comment by tomomiq** [comment]
Handing this over!

**Comment by aerugo** [comment]
related https://github.com/Edgeryders-Participio/multi-dreams/issues/440

**Comment by aerugo** [comment]
@tomomiq, @gustavlrsn - is this issue still up to date, or does it need to be revised before we assign it to someone?w

**Comment by Powersource** [comment]
Marked as 'needs testing' now since I think since this issue was opened we've added the prompt to fill in your name on first log in

**Comment by tomomiq** [comment]
hi @Powersource 

Passing back copy revisions: 

<img width="886" alt="Screenshot 2022-03-01 at 16 43 13" src="https://user-images.githubusercontent.com/1287179/156200317-9b8f7245-0598-4058-850d-3574103a285a.png">

**Comment by Powersource** [comment]
@tomomiq is the tooltip for the Name field? I don't think that's correct atm, we use it at least in a bunch of emails.

**Comment by aerugo** [comment]
I have tested this and it seems to work as expected.
