### ISSUE TITLE
Magic link button does not always work 

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#431]
This one is hard to reproduce, but it does not always work to send the magic link. Sometimes the button is simply unresponsive.

**Comment by aerugo** [comment]
I am confirming that this is still a problem, I just experienced it on mobile. Send magic link button was completely unresponsive.

**Comment by gustavlrsn** [comment]
@aerugo please reopen this if it comes back. Added some loading state to the button and blocking additional clicks if it has already been sent, could have been something around that.
