### ISSUE TITLE
Review guideline does not show up as comment

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#434]
Steps to reproduce:

- Enable bucket review in a collection
- Review a bucket and flag it

Result:

Flagging does not appear in comments.

**Comment by gustavlrsn** [comment]
Fixed but still needs a cache update fix

**Comment by Powersource** [comment]
@gustavlrsn check discord :p

**Comment by gustavlrsn** [comment]
Closing this, tracking cache update in #456
