### ISSUE TITLE
Hide emails and "real name" from non-admins

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#436]
Steps to reproduce:

Go to member list as a non-admin.

Result:

Emails are shown.

This is not a bug, just something we have not implemented yet. Emails and "real name" should be hidden from normal users. We should also hide the action prompt.

**Comment by gustavlrsn** [comment]
@aerugo Fixed. But are we sure we want to hide real name? Since we show it in other places like comments

**Comment by Powersource** [comment]
i guess when you comment you more explicitly opt in to having your name shown.

also check discord :P
