### ISSUE TITLE
Transactions list to include funds given to users

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#439]
In collections under the tab "transactions", we need to not only see contributions made to buckets, but also funds given to users accounts (allocations). This could be implemented in a very simple way for now, and then a search and filter function could be added. 

<img width="1296" alt="Screenshot 2022-01-24 at 11 19 51" src="https://user-images.githubusercontent.com/7785081/150773861-bb22c122-7860-4192-98c9-c2e21f226cc7.png">

This transaction log item should reflect all fund allocation actions taken on the "members" page as admin.

<img width="1511" alt="Screenshot 2022-01-24 at 11 22 35" src="https://user-images.githubusercontent.com/7785081/150774186-d2775f1f-12c1-4a11-bbb5-2e0d2fd1ca5c.png">

* If funds are added to a user, message should be "userA gave funds to userB"
* If funds are removed from a user, message should be "userA removed funds from userB"
* If funds are set for a user, message should be "userA reset funds for userB"
* When funds are added, removed or set for all users (click + by "balance"), one log item should be created per user

**Comment by alinauroz** [comment]
The user_id of the person who added or set the budget and the type of transaction is required to add this feature.

Right now, the budget added or set is saved inside a ledger (Allocation table) without information of who added or set the budget or what was the type of transaction (*Add* or *Set*). I would suggest adding 2 more tables to the *Allocation* table to store the user id who added or set the budget and the type of transaction.

**Comment by gustavlrsn** [comment]
Hello @alinauroz!

I think adding those two fields to the Allocation table should be fine to get going on this.

Another more extensive but perhaps more robust option is to add a completely new Transactions table, as well as an Accounts table, similar to how it is done in the previous Cobudget version (https://github.com/cobudget-old/cobudget/blob/develop/api/db/schema.rb), where they do a kind of double book keeping, an allocation is stored both as an Allocation in that table, and as a transaction in the Transaction table. But maybe this is something we could explore in the future 🤔

**Comment by alinauroz** [comment]
> 

Hi @gustavlrsn

Adding a Transaction table is fine. We save both, the contributions and allocations in the transaction table. But in this design, there can be a problem.

A separate transaction table means we are saving the same information in two different tables. This data redundancy can lead to data inconsistency. For example, in the worst case, data is saved in the Allocation table and for some reason, it is missed in the transactions table.

To handle this problem, we should either set a table which we consider true or ensure ATOMICITY.

**Comment by gustavlrsn** [comment]
Yeah, that is true. Prisma has support for transactions/batch-queries that mitigates this problem a little bit, but there is still room for mismatches of course. I think I've seen some reference in the old cobudget codebase as to how they solved that also. 

I wonder if we even could have just one Transaction table and then an Accounts table (to easily allow members, buckets, collections, and orgs to have accounts). I'm not entirely sure why the old Cobudget has allocations, contributions and transactions, but I guess there is some good reason for that.

@aerugo how big should we make this issue? Solve it quickly by adding things to the existing allocation table, or continue building out a proper financial system, inspired by the old cobudget?

**Comment by aerugo** [comment]
I would like to ask @alinauroz to propose code for the more proper solution since he has an idea about how to do it.

@alinauroz - for reference:

Like Gustav said, we are building a new version of a previous app, which you can [see schema for here](https://github.com/cobudget-old/cobudget/blob/develop/api/db/schema.rb).

**Comment by alinauroz** [comment]
I would suggest we add two columns and instead of adding a *transaction* table, we add a transaction query (Graphql). Contribution and Allocation have a different schema. 

*Advantages*
1. No Data Redundancy
2. Quick (as compared to adding table)
3. Frontend can use *transaction* query to get both allocations and contributions

*Disadvantages*
1. At the backend, we have to query from 2 different tables

This approach seems good to me. @gustavlrsn @aerugo  what do you think?

**Comment by aerugo** [comment]
I talked to @gustavlrsn now, you can go ahead with this solution @alinauroz.

**Comment by Powersource** [comment]
fixed in https://github.com/cobudget/cobudget/pull/553

**Comment by tomomiq** [comment]
Reviewed and closing! 

Made a new ticket to improve the usability, punted to the future. https://github.com/cobudget/cobudget/issues/570
