### ISSUE TITLE
[FEATURE] Remove member from org

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#442]

**Comment by Powersource** [comment]
thinking out loud: we currently have logic for removing a round member from a round, i think i'm just gonna reuse that logic and call it for all the groupmember's rounds in that group, followed by removing their groupmember entry

**Comment by Powersource** [comment]
realized we shouldn't actually remove a user from the rounds in a group when removing them from the group. so that makes things simpler (at least for me lol)

**Comment by tomomiq** [comment]
LGTM
