### ISSUE TITLE
Switch to AGPL3 + additional terms 

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#444]
New license based on Pretix license: https://docs.pretix.eu/en/latest/license/faq.html

**Comment by Powersource** [comment]
More related links

https://open.sentry.io/licensing/  
https://blog.sentry.io/2019/11/06/relicensing-sentry  
https://github.com/pretix/pretix/blob/master/LICENSE  
https://pretix.eu/about/en/blog/20210412-license/

**Comment by Powersource** [comment]
when picking a new license i think it's good if we roughly specify what we want it to accomplish. @aerugo could you write a short list of things you want it to do?

**Comment by Powersource** [comment]
also TODO: look at mongodb's license

**Comment by aerugo** [comment]
@Powersource 
My thinking right now is that I would like to achieve this:

 - We own and control the name Cobudget, meaning that nobody else can sell services under that company name
 - We also name the software Cobudget and make sure that it is clearly identified as such in the frontend - with the name hard-coded and links pointing back to our landing page where we sell the SaaS. This means that if anyone self-hosts Cobudget, they will be advertising the cobudget.com service. 
 - If someone runs Cobudget unmodified, they can do whatever they want, including linking it to their own Stripe. However, they will then be advertising cobudget.com through doing so.
 - If someone runs a modified version of Cobudget, there are terms they need to follow. They must keep the link back to cobudget.com intact, and if they offer their service as a SaaS, they must also make the changes available. 

In my mind, this gives the community a lot of flexibility while making sure that they cannot simply rename the project "CowBudget" and start selling it as such. 

This is the model that Pretix has gone for: https://docs.pretix.eu/en/latest/license/faq.html

**Comment by aerugo** [comment]
Note however that the above is basically just based on that I thought the Pretix license was pretty clever. I'm open to other strategies.

**Comment by Powersource** [comment]
Haven't had time to read the pretix license thoroughly yet but I think for the above list of requirements we basically have all of them already with our trademark+agpl, except for the "They must keep the link back to cobudget.com intact". This is basically how mozilla does it with firefox, and they even have a looser license https://www.mozilla.org/en-US/foundation/trademarks/policy/

**Comment by aerugo** [comment]
If you would want to look at the Pretix license additions to AGPL, that
would be quite useful.
But does our current license really make sure that someone can’t just
modify the code to rename the platform “CowBudget” and link to their own
SaaS sales funnel at cowbudget.com?

**Comment by Powersource** [comment]
Ah yeah no, we wouldn't be protected from that, just the things in the list. That point requires something more

**Comment by aerugo** [comment]
As I understand it, that’s what the Pretix license seems to be about. But I
would like to have another set of eyes on it to verify.

**Comment by Powersource** [comment]
Read up on it now. The pretix license looks pretty good, and I'd be fine with us adopting it. Although I wonder if it limits things enough, since the only real change is that they have to keep our name in the footer, and I don't know if anyone really looks there? But maybe this is a good start and we could change it again in the future if we want.

**Comment by Powersource** [comment]
made a pr, fwiw https://github.com/cobudget/cobudget/pull/492
