### ISSUE TITLE
Contributor can always see their totals during contribution process.

### ISSUE THREAD

**Issue by derekrazo** [cobudget/cobudget#45]
We've gotten lots of feedback that the app annoyingly makes people scroll back and forth to see how much monies they have left to allocate.

We can fix this by scrollfixing a tinier version of the round summary that currently exists to the top of the page when scrolling.

Tiny round summary needs design.

**Comment by derekrazo** [comment]
@jonlemmon - what do you think the MVP of this ticket is?

**Comment by jonlemmon** [comment]
TBH it's pretty hard to say without putting design time in. The only thing
I can think of off the top of my head is a single-column layout.

**Comment by ahdinosaur** [comment]
from Malcolm: "mini feature request: I’d love it if my funds balance stayed visible as I scrolled down the screen."
