### ISSUE TITLE
Fix cache updates and pagination

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#456]
- [ ] collection member list
  - [x] update cache when approving members
  - [ ] fix pagination
- [x] when creating a coll
- [x] update cache when leaving a flag
- [x] clearing a flag
- [x] fund a bucket and then go to another page that lists how much funds you have left, the number has not been updated
- [x] create a bucket and it doesn't appear on the coll page

**Comment by aerugo** [comment]
What's the status on this @Powersource ?

**Comment by Powersource** [comment]
@aerugo i put it on ice because we were missing some member invite features but if that's in now i could pick it back up this week
