### ISSUE TITLE
Fix the colors of the menu

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#457]
![Image 2021-11-30 at 2 12 03 PM](https://user-images.githubusercontent.com/1287179/144053660-acf6a0a5-497b-4b0b-b0b6-56f184d62019.jpg)

**Comment by Powersource** [comment]
fixed by https://github.com/cobudget/cobudget/commit/dfbc2aa5b9136abf8e4c7c92e785b6c6de8135c7
