### ISSUE TITLE
Empty UI box in bucket page for regular member

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#459]
![image](https://user-images.githubusercontent.com/1552194/144055770-082a174f-5650-43bf-a7b0-bfd3e2e1ed85.png)

**Comment by Powersource** [comment]
hmm i could reproduce this a minute ago but now it's gone

**Comment by Powersource** [comment]
@tomomiq @gustavlrsn do you remember how to reproduce this?

**Comment by gustavlrsn** [comment]
Can't reproduce either. I guess we can close it
