### ISSUE TITLE
Update name in Privacy Policy and Terms

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#462]
Change platoprojects.org to Cobudget 

https://cobudget.com/privacy-policy
https://cobudget.com/terms-and-conditions

and keep SenseStack as the org until the new entity is ready?

**Comment by skoteskote** [comment]
I'll fix

**Comment by skoteskote** [comment]
Name updated to cobudget.com. Org is still Sensestack and mail info@platoproject.com
