### ISSUE TITLE
Creating bucket when creation date is passed gives bad error message

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#465]
> Cannot read properties of null (reading 'id')
Error message should say bucket creation date is passed.

Should also disable the button to prevent it anyhow.

**Comment by Powersource** [comment]
I can't reproduce this, the Create bucket button is gone for me after the date is passed. The code also contains `      if (!bucketCreationIsOpen) throw new Error("Bucket creation is not open");` so feels like this shouldn't happen in this case. I wonder if this is another case of https://github.com/cobudget/cobudget/issues/468#issuecomment-983681314
