### ISSUE TITLE
Make max budget easier to have optional

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#466]
Also sometimes on new buckets??

**Comment by Powersource** [comment]
Not sure if it's the one you mean but when testing now the only bug I notice is that you are forced to set a max budget that is above your min budget

**Comment by Powersource** [comment]
it's already optional in the schema so prob just need to fix the form

**Comment by Powersource** [comment]
or hmm it actually works if you remove the default 0 that gets put in there. probably just need to change it to default to empty string

**Comment by Powersource** [comment]
I pushed https://github.com/cobudget/cobudget/commit/7c00dbc19d15529a6c48480ea05f49e15a864950 which I think fixes this. Can you confirm @gustavlrsn @tomomiq if you think the bug is fixed?

**Comment by gustavlrsn** [comment]
Sweet. Seems to work for me!
