### ISSUE TITLE
Missing error message for text input in Fund modal

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#467]
no error message happens 

![Image 2021-11-30 at 3 03 49 PM](https://user-images.githubusercontent.com/1287179/144062427-98ef671a-683f-483f-8a3c-15d3b13ba384.jpg)

**Comment by Powersource** [comment]
now gives you an error message if you try to submit something weird 33707b16b06373775523d9bff38fc4d8761bb813
