### ISSUE TITLE
Fix always getting first orgMember and collectionMember

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#474]
I think this 

https://github.com/cobudget/cobudget/blob/7e21ed27842e80f834329f71fce375dba8bf33ea/ui/server/graphql/resolvers/helpers.ts#L48-L49

might be causing these bugs

* https://github.com/cobudget/cobudget/issues/465
* Create a new member, then that member can't join a collection

i think the fix is two steps:
* [ ] deduplicate all the logic that gets orgMembers and collectionMembers, this bug is duplicated in a few places. they should all use the helper function
* [ ] fix the bug in the helper function

**Comment by gustavlrsn** [comment]
https://github.com/cobudget/cobudget/blob/7e21ed27842e80f834329f71fce375dba8bf33ea/ui/server/graphql/resolvers/helpers.ts#L33-L35
I've been thinking this `include: { collectionMemberships: { where: { collectionId } } }, ` should only add a single collection member that matches both the orgMembership and that collectionId, but maybe there is some unclear thing there

Fixing this in the removing org dependency thing right now

**Comment by Powersource** [comment]
@gustavlrsn ah i didn't think about that. So I guess this is a workaround because includeFirst doesn't exist.

but yeah we should at least deduplicate the logic, reduce the surface area for bugs
