### ISSUE TITLE
Adding co-creators does not work

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#488]
Steps to reproduce:
 - Go to https://cobudget.com/c/burberland/ckxasdk82007408jx9aiyceaf as an admin
 - Click pen to add co-creator

Result:
 - "An unexpected error has occurred."

**Comment by aerugo** [comment]
@gustavlrsn I made you admin of the group so you can test

**Comment by gustavlrsn** [comment]
Fixed
