### ISSUE TITLE
Make message for unique slug more user friendly

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#490]
<img width="1748" alt="Screenshot 2021-12-19 at 19 58 15" src="https://user-images.githubusercontent.com/7785081/146697805-473d3765-34d0-4fe7-afbf-d8aef10741d5.png">

Since we made collections into root entities, a lot of users will run into this message as they create test collections called "test", or "my collection" or "my group". It needs to be more user-friendly - ideally automatically suggesting a slug that is available.

**Comment by gustavlrsn** [comment]
Turned the error message into "Slug is already taken"
