### ISSUE TITLE
User approval of persistent authentication cookie

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#495]
Cobudget uses persistent cookies to authenticate a returning user so the user doesn't have to log in every time they visit the site. Persistent cookies are not regarded as "necessary or essential cookies" by [EU cookie law](https://en.wikipedia.org/wiki/Privacy_and_Electronic_Communications_Directive_2002), hence we need to have the users explicit approval to set this cookie. 

**Solution A:** 
Add a cookie banner via Iubenda (the legal service we are using for ToS and such.) 
Pros: Future proof if we need to set more cookies down the line for various reasons, super easy to just add new ones in Iubenda and it updates the banner automatically. 
Cons: Intrusive and annoying. 

**Solution B:** 
Add a "Remember me" button when the user log's in. By checking this box the user gives explicit consent for us to set the cookie. This seems to be a common workaround.
Pros: Not intrusive.
Cons: Doesn't allow us to set any other cookies than the one for persistent authentication.

**Comment by skoteskote** [comment]
@aerugo this should probably be in place before launch on 15th?

**Comment by skoteskote** [comment]
Decision from tech meeting 3/1/21: Solution B. Also because this makes it easier to use the platform from public computers.

**Comment by gustavlrsn** [comment]
Trying this approach
https://github.com/expressjs/cookie-session/issues/21#issuecomment-169401680

**Comment by francesca-sp** [comment]
Checked with Tomomi and all good! As an FYI, we think that the extra cookie consent pop up will be needed fairly soon though, when we add analytics to the website landing page. We will put up a separate issue for this.
