### ISSUE TITLE
Can't edit comments with new editor

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#510]
Steps to reproduce:

- Go to https://cobudget.com/c/burberland/ckxasdk82007408jx9aiyceaf as admin of that round
- Try to edit a comment

Result:
> Application error: a client-side exception has occurred (see the browser console for more information).

Console:
> TypeError: Cannot read properties of undefined (reading 'split')

**Comment by Powersource** [comment]
strange, still works in dev. will inspect more

**Comment by Powersource** [comment]
fixed by https://github.com/cobudget/cobudget/commit/ca5f26bba7abde5fe12d29b9076e42c7de9a4ec9

code should get cleaned up a bit more with the followup pr
