### ISSUE TITLE
Comment pane extends outside element on mobile

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#511]
Steps to reproduce:

- Go to the comment pane on a bucket on mobile 
- Swipe to the left

Result:

Comment tool seems to invisibly extend to the right, making the container div at least twice as large as it should be

**Comment by Powersource** [comment]
Hmm only reproducibile in chrome.

And at least this seems to be the only visual bug, the editor is still contained where it should be etc

**Comment by aerugo** [comment]
I noticed this problem on iOS Safari, so possible it only works fully as expected on Firefox.

**Comment by aerugo** [comment]
Did you test in an iOS safari emulator? 
Still a problem on my side. Tried logging in a new incognito tab.

**Comment by Powersource** [comment]
i don't think i have access to one of those, tried in chrome though. very strange. try hard-refreshing (however you do that)

**Comment by aerugo** [comment]
I just tried on Safari on Mac, and the problem is there. Chrome works as expected.

**Comment by Powersource** [comment]
gonna hand this over to Gustav instead

**Comment by gustavlrsn** [comment]
Pushed a fix, seems to work now
