### ISSUE TITLE
[FEATURE] Invite links

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#513]
<img width="1116" alt="Screenshot 2022-04-07 at 11 51 36" src="https://user-images.githubusercontent.com/7785081/162176337-bdf60e39-00cb-4108-89ea-06dc406a24f6.png">

<img width="1093" alt="Screenshot 2022-04-07 at 12 04 04" src="https://user-images.githubusercontent.com/7785081/162176360-99ed1cf2-4812-4767-9538-be34266f4fe6.png">

- A new invite link is created with the "Create invite link" button. Before it is created, it does not exist.
- An invite link can be sent to existing cobudget users and to new users. If it is sent to new users, it first lets you register an account. See the regular invite user by email flow.
- If the invite link is deleted, it should stop working. If a new invite link is created, it has another url. This is to allow round owners to correct if an invite link has been sent to the wrong people by mistake.
- "Cancel" should be renamed to "Close" since it is otherwise confusing for a user who might think that their invite link is not saved if they "cancel" the prompt.

**Comment by aerugo** [comment]
@alinauroz - testing this feature, and I get this error when trying to join by invite link on staging:
<img width="1380" alt="Screenshot 2022-04-28 at 12 16 19" src="https://user-images.githubusercontent.com/7785081/165732129-dfadcf1b-6539-4179-a10d-7667e2e868ab.png">

**Comment by gustavlrsn** [comment]
Might be related to the type error I fixed that errored out the building of the project. Added `String()` around the inviteNonce because the sign function expected a `string`

**Comment by gustavlrsn** [comment]
Updating the interface
