### ISSUE TITLE
Title formatting error for special characters in emails

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#516]
In the email notifications, characters such as an apostrophe are not being resolved correctly, see example in this screenshot. 

![image](https://user-images.githubusercontent.com/3641828/149943165-85548b3e-7603-4527-98ea-1acc96a3de35.png)

**Comment by Powersource** [comment]
should be fixed by https://github.com/cobudget/cobudget/commit/6b666265a26f360720954552721729787edb2163 and https://github.com/cobudget/cobudget/commit/86bcef68c9978a217698837d3e12db021ba361ba
