### ISSUE TITLE
Standard about text for a new collection is not shown and unable to edit

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#520]
**Describe the bug**
When creating a new collection, the standard about text is no longer shown and I am unable to edit it.

**Comment by gustavlrsn** [comment]
@Powersource looks like the `EditableField` component is hardcoded to only work for the `info` field: https://github.com/cobudget/cobudget/blob/main/ui/components/EditableField.tsx#L30-L41

Is this way of registering fields to `react-hook-form` because we cant use an inputRef on the Wysiwyg?

**Comment by aerugo** [comment]
<img width="889" alt="Screenshot 2022-01-23 at 19 25 44" src="https://user-images.githubusercontent.com/7785081/150694730-a65602c3-3e54-4295-bc1d-1d7b6fc79c6c.png">

It also looks like this when not logged in.

**Comment by Powersource** [comment]
just pushed https://github.com/cobudget/cobudget/commit/d327a80ebf893c651ee248fce09446a4db9cabe3 which should fix it

**Comment by Powersource** [comment]
also here's the fix for not getting the about.js file as a result in vscode when refactoring this before https://github.com/cobudget/cobudget/commit/5ad1b6c16a3b1467753a7d78a264a4c2bf2cd59d
