### ISSUE TITLE
[BUG] Change "collection" to "round" in general settings

### ISSUE THREAD

**Issue by DavidsBees** [cobudget/cobudget#526]
**Describe the bug**
Legacy wording used in settings

**To Reproduce**
1. Go to Settings -> General
2. Scroll down to 'Archive collection'

**Expected behavior**
Wording to be "Archive Round"

**Screenshots**
![collection](https://user-images.githubusercontent.com/80971095/151400796-e9420494-f1bf-4c6d-b1b5-d6aaea8c3332.PNG)

**Comment by aerugo** [comment]
This should be covered by #597
