### ISSUE TITLE
[BUG] Cannot accept member request to join a group

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#527]
**Describe the bug**
When a user has requested to join a group with that joining policy, clicking on the "approve" button brings up a popup "are you sure you would like to approve", but then once you click "ok", nothing happens. Tried to reload the page, but this did not fix it either. I am not an admin in this group

**To Reproduce**
1. Go to members list in a group where someone has requested to join, in which you are not admin
2. Click on "approve" of that member
3. Click "ok" when the popup appears

**Expected behavior**
I was expecting the person to be added to the member list, OR if I am not allowed to do this action, then I should not see the request at all. 

**Screenshots**

![image](https://user-images.githubusercontent.com/3641828/151401342-a7601454-0548-4537-b939-c267bd3235ab.png)

![image](https://user-images.githubusercontent.com/3641828/151400741-e800366c-a0d1-4d22-a42d-ff83eb3c2972.png)

**Browser and device (please complete the following information):**
 - Browser: Brave
 - Device: windows

**Comment by Powersource** [comment]
This seems to be a round fwiw

**Comment by Powersource** [comment]
now we hide the 'requests to join' list to non-admin members

**Comment by tomomiq** [comment]
LGTM
