### ISSUE TITLE
[BUG] Review enabled leads to error on showing bucket

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#532]
Bucket review seems to trigger an app error when visiting a bucket.

Steps to reproduce:

- Create collection
- Create a bucket
- Add guidelines to collection
- Enable review
- Go to bucket

Result:

<img width="1569" alt="Screenshot 2022-01-29 at 17 17 19" src="https://user-images.githubusercontent.com/7785081/151670547-4a8bf260-d988-49d2-8979-96e22f7a73fd.png">

**Comment by gustavlrsn** [comment]
Fixed
