### ISSUE TITLE
[FEATURE] Update all words to current terminology 

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#542]
Since the project started, we have changed the terminology a few times. We have now decided on the terms we will use. There are still many references to the old terms in the backend and and frontend, both in the code and the UI. 

Make sure that the following terms are consistently applied across the codebase. This means updating the terms in the UI, in code references, in comments, resolvers, queries, etc. 

**Bucket**: Used to be called a "dream". Currently both terms occur in the code. It should always be "bucket", and "buckets" in plural.
**Round**:  Is currently called "collection", and was previously called "event", and both names occur in the code now. Will now be renamed "round", and "rounds" in plural. 
**Group**: Used to be called "organization" and should now be renamed "group".

Notes: 

* Ignore code in cobudget/ui/server/mongo/ as this is only there for legacy support.
* Make use of Prisma migrations to rename columns in the database.
* Do not rename table/model names and relationship fields
* **Make sure to test migrations carefully so that no tables are dropped by accident**

**Comment by Powersource** [comment]
Rounds are also sometimes called 'event's in the code, should also be changed.

**Comment by gustavlrsn** [comment]
Changing the names of fields/columns in the db should be fine and easy with the Prisma migration tool. Never tried changing the name of the table itself, maybe it handles that as well

**Comment by aerugo** [comment]
Noted @gustavlrsn, I have updated the issue. Is there anything where the old names should not be touched in the code?

**Comment by gustavlrsn** [comment]
I think table/model names and maybe also relationship fields in the prisma schema are the important ones to not touch.

**Comment by alinauroz** [comment]
> Changing the names of fields/columns in the db should be fine and easy with the Prisma migration tool. Never tried changing the name of models/tables, maybe it handles that as well

By default, renaming a column with prisma drops the column and then creates new column. This will cause loss of data.

**Comment by alinauroz** [comment]
A solution is to create a prisma migration for renaming the column without running it and then modifying the migration files to not to drop the column.

**Comment by alinauroz** [comment]
@aerugo can you send discord link here. Sending links is banned on the *other* website.

**Comment by aerugo** [comment]
Sent it to you on email @alinauroz

**Comment by gustavlrsn** [comment]
> By default, renaming a column with prisma drops the column and then creates new column. This will cause loss of data.

> A solution is to create a prisma migration for renaming the column without running it and then modifying the migration files to not to drop the column.

Right, that's true! Forgot that you have to alter the migration file manually to rename a column and not simply drop it and create a new one.

**Comment by Powersource** [comment]
related https://github.com/cobudget/cobudget/issues/559
