### ISSUE TITLE
[BUG] Questions default to short text when edited

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#543]
**Describe the bug**
Settings - Questions - Question modal defaults back to Short text after any edit of question.

**To Reproduce**
1. Go to Settings - Questions for a round.
2. Add a question, set it to Long text.
3. Save.
4. Edit the question and change eg the title. 
5. The question automatically change from long text to short text.

**Expected behavior**
The question should not change the desired text length without explicit user interaction.

**Browser and device (please complete the following information):**
 - Browser Brave, Safari
 - Device and/or OS: Mac

**Comment by skoteskote** [comment]
@aerugo Your choice where to put it, but it's very annoying and I guess an easy fix.

**Comment by aerugo** [comment]
Seems like a pretty critical bug, so I put it in our current milestone.

**Comment by tomomiq** [comment]
Thank you @alinauroz !
