### ISSUE TITLE
[FEATURE] Replace favicon with Cobudget logo

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#547]
**Describe the feature**
We can still see the Dreams favicon in the browser. It would be good to replace it with the cobudget one - ideally by March 1, latest for the launch in May.

**Comment by francesca-sp** [comment]
![Logo_background](https://user-images.githubusercontent.com/3641828/153588559-5195f756-a296-4c23-a791-05563c8eac78.png)

**Comment by aerugo** [comment]
Done.
