### ISSUE TITLE
[BUG] Error when going from group page to round page

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#550]
**To Reproduce**

1, be me logged in and go to https://cobudget.com/jacob-org
2. click on the only round in it i have
3. the page just loads with the text "Application error: a client-side exception has occurred (see the browser console for more information)." if you load the round page directly it works

you can also do:

1. load the same group page
2. using the top bar navigation menu, go to an unrelated round
3. get the same error

**Comment by Powersource** [comment]
the console isn't super useful since in prod it's all garbled but it does say "TypeError: (intermediate value).collection is null"

**Comment by Powersource** [comment]
Chrome logging a bit differently: "TypeError: Cannot read properties of null (reading 'bucketStatusCount')"

**Comment by Powersource** [comment]
Should be fixed by https://github.com/cobudget/cobudget/commit/aa3a34dbb1257ff1b02b77085de28622eac104d6

**Comment by Powersource** [comment]
seems to be fixed

**Comment by aerugo** [comment]
Well done!
