### ISSUE TITLE
[FEATURE] Make round members list searchable by name

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#555]
**Describe the feature**
The current search function of the members list only allows search by handle, which is very impractical, since people often don't have handles that relate to their name and the person searching is likely to not know it. 

We need the round member list to include searching by first and last name, and ideally also email address. 

This issue relates to this previous one: https://github.com/cobudget/cobudget/issues/369

**Comment by tomomiq** [comment]
Thanks @Powersource
