### ISSUE TITLE
[BUG] Rename "Join Org" to "Join Group"

### ISSUE THREAD

**Issue by eden-gt** [cobudget/cobudget#558]
**Describe the bug**
When going to a new group page - the joining button term needs replacing

**To Reproduce**

1. Go to a new group page where you are not a member (e.g. https://cobudget.com/greaterthan) 

2. See CTA at top right hand corned "Join Org"

**Expected behavior**
CTA at tope right hand corner should read "Join Group"

**Screenshots**
<img width="1002" alt="Screenshot 2022-02-15 at 13 43 51" src="https://user-images.githubusercontent.com/94849002/154074518-da95fa46-ed58-4b21-b4df-583d3becc108.png">

**Browser and device (please complete the following information):**

- Browser: chrome
- Device: Mac

**Comment by aerugo** [comment]
Covered by #597
