### ISSUE TITLE
Add concept of accounts and transactions in database

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#562]
Adding transactions and accounts in the database will allow us to better manage funds, for example, a round or a group can have a balance. This is inspired by the old Cobudget's data model that includes allocations, contributions, accounts and transactions.

A member should have
- incoming account (represents what this member has put in themselves)
- status account (what the member currently has on their own account)
- outgoing account (what the member has been paid)

A bucket, round and group should have
- status account

**Comment by gustavlrsn** [comment]
This also enables us to do a "full"  and easy migration of the old cobudget data.

**Comment by aerugo** [comment]
I believe this is done.
