### ISSUE TITLE
[DEV] Deploy to a staging environment

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#571]
- [x] Create staging database
- [x] Deploy a branch `staging` to `staging.cobudget.com`

**Comment by Powersource** [comment]
this would be great

**Comment by Powersource** [comment]
We have a staging deployment but last i checked it didn't work like i expected, when i merged things to main things were still deployed directly to prod. IMO we need to
1. Make `main` the branch the branch that deploys to staging
2. Make a new branch `prod` that deploys to prod

**Comment by aerugo** [comment]
I thought this was done already?

**Comment by Powersource** [comment]
IMO no, see my comment above

**Comment by aerugo** [comment]
I think we need to work like this, if we go with 'main' = staging and 'stable'/'prod' = production:

- Everyone works from the assumption that they must keep their own WIP branches in sync with 'main'.
- Before a PR is made to 'main' it is the responsibility of the one who submits it to solve merge conflicts
- In some cases, if two people are working on large WIP features that touch the same code, they may want to also keep their respective branches in sync with each other
- 'main' is merged into 'prod' after testing, probably a couple of times per month or so.
- Small fixes that are pushed straight to 'prod' need to then be immediately merged into 'main' from 'prod'

I think that should keep us sane?

**Comment by aerugo** [comment]
We close this once we close #616

**Comment by Powersource** [comment]
I don't think so, see my comment above.

Jacob

**Comment by Powersource** [comment]
Lool. I sent that email on March 14th (to this issue). No idea why it showed up now.
