### ISSUE TITLE
[BUG] Guidelines don't show up in the right order

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#576]
**Describe the bug**
A user reported to me that they put up guidelines, but that on the About page, they don't show up in the correct order. I reproduced this bug by checking the [Burberland dreams](https://cobudget.com/c/burberland/about) group.

**To Reproduce**
1. Go to 'Settings" > "Guidelines"
2. Setup a series of guidelines in a specific order
3. Then go to the tab "about" and compare the order on the about page with the guidelines page
4. Error: the guidelines seem to show up in a random order

**Expected behavior**
One would expect that the guidelines show up in the exact order as when setting them up, especially because there is a feature that allows you to drag and drop guidelines to be in the order you would like. 

**Browser and device (please complete the following information):**

- Browser: Chrome
- Device: Windows

**Comment by francesca-sp** [comment]
Here is another very visible example of the jumbled order, since the users of this group enumerated their guidelines: https://cobudget.com/c/perspectivity/about

**Comment by Powersource** [comment]
fix should be deployed in a few minutes

**Comment by francesca-sp** [comment]
Looks good! Closing the issue.
