### ISSUE TITLE
[BUG] If I delete myself from a round, application crashes (on members + transaction pages)

### ISSUE THREAD

**Issue by eden-gt** [cobudget/cobudget#582]
**Describe the bug**
If I delete myself from a round, application crashes (on members + transaction pages)

**To Reproduce**

1. Go to a members tab of a round 
2. Click on yourself
3. Press Delete
4. Confirm delete with pop up 
5. App crashes

**Expected behavior**
A blank page telling me:
"Oops, something went wrong! Go back to the homepage".

**Screenshots**
<img width="940" alt="Screenshot 2022-03-01 at 14 56 35" src="https://user-images.githubusercontent.com/94849002/156192972-86325e06-328e-43d8-979d-90284c209db4.png">

<img width="932" alt="Screenshot 2022-03-01 at 14 54 50" src="https://user-images.githubusercontent.com/94849002/156192997-ddb3a041-a350-451c-9563-32cf34dbf8d1.png">

**Browser and device (please complete the following information):**

- Browser: chrome
- Device and/or OS:  Mac & PC

**Comment by tomomiq** [comment]
Confirmed I could successfully delete myself.
