### ISSUE TITLE
[BUG] error when adding balance to unverified member

### ISSUE THREAD

**Issue by alanna** [cobudget/cobudget#587]
<img width="463" alt="Screen Shot 2022-03-02 at 3 44 48 PM" src="https://user-images.githubusercontent.com/5498878/156285011-f60f8f56-3d94-494e-9e3a-71c6ac1972fb.png">

This is what I saw when I tried to add balance to a member who had been invited but had not yet accepted.

However, when I refreshed, it seems the balance was actually added.

**Comment by Powersource** [comment]
this seems to be the same as https://github.com/cobudget/cobudget/issues/589 which is now fixed
