### ISSUE TITLE
[BUG] Error message on the about pages

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#590]
**Describe the bug**
The second half of the about page that pulls from the "settings" is not appearing, and it says there is an error. 

**To Reproduce**

1. Go to any cobudget round 
2. Click on 'About'
3. See error on second half of the page

**Screenshots**
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/3641828/156385928-7a9a332b-2281-4592-b90c-5480792d16b3.png">

**Browser and device (please complete the following information):**

- Browser Brave
- Windows

**Comment by gustavlrsn** [comment]
Fixed
