### ISSUE TITLE
[BUG] Application Error on members & transactions page that I don't have access to

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#600]
**Describe the bug**
Error when going to certain round pages if you are a group admin who is not a member of the round. 

**To Reproduce**

1. Go to a public 'Round' you are not a member of, in a group where you are an admin
2. Click on ''Members" and "Transactions" and Settings
3. See application error shown below for members and transactions page, and on the settings pages you see the full page and can edit.

**Expected behavior**
When entering a round I am not a member of, I expect to not see tabs I don't have access to, in this case the Transactions and Settings tab. When going on the members tab, I should see the message telling me I cannot see it, because I have not joined ("You need to be a member of this round to see the member list). It needs to look the same as what is visible for users who are not logged in (in a public group). 

**Screenshots**
![image](https://user-images.githubusercontent.com/3641828/157703464-855c542d-0aad-4bae-83c9-f5ea8d3e572d.png)

**Comment by Powersource** [comment]
on staging in a few min

**Comment by eden-gt** [comment]
This is fixed!
