### ISSUE TITLE
[FEATURE] Log in with Facebook and Google

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#611]
**Describe the feature**
A user should be able to log in with a Facebook or Google account. We briefly had this in the old version but it got removed I think? 

This is especially useful for use cases like eg Malmö Tillsammans where they have very large groups of users who have very low technical knowledge. This might surprise you, but for some people "just check your mail!" isn't as straightforward as it is for us. The ability to log in with one's Facebook account lowers the entry threshold immensely. 

* [ ] facebook https://github.com/cobudget/cobudget/pull/642
* [ ] google https://github.com/cobudget/cobudget/pull/658

**Comment by Powersource** [comment]
"This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs."

**Comment by Powersource** [comment]
"The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."

**Comment by Powersource** [comment]
note, when testing this in staging eventually:
* test the flow where a user denies the `email` permission
* test signing up using a facebook account with an email address that doesn't yet have a normal cobudget account

**Comment by Powersource** [comment]
facebook login can be tested now. see comment above for testing tips. if testing passes then don't close the issue (since we still have google left) but instead check the box in the issue description

**Comment by aerugo** [comment]
I get this error when I try to sign up with Facebook. This Facebook account is associated with an email that is not registered on Cobudget staging or production.

<img width="1287" alt="Screenshot 2022-03-31 at 14 26 23" src="https://user-images.githubusercontent.com/7785081/161054720-a381163f-9da5-4074-845b-b2412f706a10.png">

**Comment by Powersource** [comment]
@aerugo A fix should be deployed on staging now

**Comment by Powersource** [comment]
google sign in is also on staging now

**Comment by tomomiq** [comment]
Confirming that logging in with Facebook and Google accounts, when I have a Cobudget account with the same e-mail, works. 

@Powersource can this say Cobudget instead of Plato Project..? 

<img width="1365" alt="Screenshot 2022-04-04 at 22 22 17" src="https://user-images.githubusercontent.com/1287179/161625751-a248481c-9743-4c90-b9fc-0da08a4219f7.png">

**Comment by tomomiq** [comment]
Got it. Fran and I tested login (to an existing cobudget account that was set up with the same email) and account creation for both FB and Google i.e. functionality-wise, it seems to be working great! 

Can we squeeze in some usability improvements as part of this rollout? (pls feel free to break it out as a new issue if that makes more sense!) 

* Use a black button for the magic link (the two shades of blue feels confusing) 
* Add "or" to create a stronger separation 
* Differentiate copy of FB/G between the sign up and login pages 
* Add the ability to switch between the two pages if you do/don't have an account 

<img width="1116" alt="Screenshot 2022-04-05 at 14 55 08" src="https://user-images.githubusercontent.com/1287179/161758322-a416c02d-1de5-41bb-aefc-39b89697f4fe.png">

**Comment by Powersource** [comment]
Moved that to a new issue here https://github.com/cobudget/cobudget/issues/669
