### ISSUE TITLE
[FEATURE] Ability to replace the word "bucket" with other terminology

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#618]
**Describe the feature**
An Admin should be able to change the word "bucket", so it fits with their organization's existing terminology. 

A new settings page should be added, called "Terminology". Here, the admin can set the term that is used for 'bucket' in the round. There should be two field, one for singular "bucket" and the other for plural "buckets". Bucket/buckets are the custom values.

This settings page should only be visible for rounds in orgs where a special field 'terminology' has been set to True in the database. See the [Discourse settings implementation](https://github.com/cobudget/cobudget/blob/ccbfce902bc12e183cc9aecce15ba2002d612fb1/ui/components/EventSettings/index.js) for another example of this logic. 

Different orgs have different terminologies. Ours is "bucket" or "dream". Some uses "project" or "idea" or "application". An org needs to be able to fit the wording to their own terminology to make the platform fit into their processes. 

This setting should be per round, and default set on org level.

### **Occurrences of the word "bucket":**

Round view: 
* New bucket button [ui/components/NewDreamModal.js](https://github.com/cobudget/cobudget/blob/b6548d8f06eb1331b35dd5fd73a39ef95f1f4ce0/ui/components/NewDreamModal.js "ui/components/NewDreamModal.js") line 50 [ui/pages/[org]/[collection]/index.tsx](https://github.com/cobudget/cobudget/blob/3a2f07d1d627825c0f5c222a1b0a02a649649f36/ui/pages/%5Borg%5D/%5Bcollection%5D/index.tsx "ui/pages/[org]/[collection]/index.tsx") line 278 

Round/About: 
* Contributions made to bucket open for funding, [ui/components/About/index.tsx line](https://github.com/cobudget/cobudget/blob/9888090bbe50fbf7a1b70d150fbd3542aa7dc7ae/ui/components/About/index.tsx) line 162
* Contributions made to funded buckets, [ui/components/About/index.tsx line](https://github.com/cobudget/cobudget/blob/9888090bbe50fbf7a1b70d150fbd3542aa7dc7ae/ui/components/About/index.tsx) line 168

Round/Settings
* Bucket Review [ui/components/EventSettings/index.js](https://github.com/cobudget/cobudget/blob/ccbfce902bc12e183cc9aecce15ba2002d612fb1/ui/components/EventSettings/index.js "ui/components/EventSettings/index.js") line 16
* If you have set up guidelines you can allow users to review each others buckets according to them. [ui/components/EventSettings/BucketReview/index.js](https://github.com/cobudget/cobudget/blob/ccbfce902bc12e183cc9aecce15ba2002d612fb1/ui/components/EventSettings/BucketReview/index.js "ui/components/EventSettings/BucketReview/index.js") line 30
* Add questions for buckets to answer. [ui/components/EventSettings/CustomFields/index.js](https://github.com/cobudget/cobudget/blob/ccbfce902bc12e183cc9aecce15ba2002d612fb1/ui/components/EventSettings/CustomFields/index.js "ui/components/EventSettings/CustomFields/index.js") line 16
* Describe your bucket (default text in Description question) - couldn't find
* Require moderator approval of buckets before funding [ui/components/EventSettings/Granting/SetRequireBucketApproval.js](https://github.com/cobudget/cobudget/blob/9a54ca0df91fae60a47bb40809104e80a4ce08c0/ui/components/EventSettings/Granting/SetRequireBucketApproval.js "ui/components/EventSettings/Granting/SetRequireBucketApproval.js") line 41, and  [ui/components/EventSettings/Granting/index.js](https://github.com/cobudget/cobudget/blob/9a54ca0df91fae60a47bb40809104e80a4ce08c0/ui/components/EventSettings/Granting/index.js "ui/components/EventSettings/Granting/index.js") line 143
* Max. amount to one bucket per user [ui/components/EventSettings/Granting/SetMaxAmountToDream.js](https://github.com/cobudget/cobudget/blob/ccbfce902bc12e183cc9aecce15ba2002d612fb1/ui/components/EventSettings/Granting/SetMaxAmountToDream.js "ui/components/EventSettings/Granting/SetMaxAmountToDream.js") line 35 [ui/components/About/index.tsx](https://github.com/cobudget/cobudget/blob/9888090bbe50fbf7a1b70d150fbd3542aa7dc7ae/ui/components/About/index.tsx "ui/components/About/index.tsx") line 92 [ui/components/EventSettings/Granting/index.js](https://github.com/cobudget/cobudget/blob/9a54ca0df91fae60a47bb40809104e80a4ce08c0/ui/components/EventSettings/Granting/index.js "ui/components/EventSettings/Granting/index.js") line 154
* Bucket creation closes - couldn't find
	
Emails
* [ui/server/services/EmailService/email.service.ts](https://github.com/cobudget/cobudget/blob/fec3da07a12e6771562f41529bf30b0643c767cd/ui/server/services/EmailService/email.service.ts "ui/server/services/EmailService/email.service.ts") line 481

**Comment by aerugo** [comment]
@alinauroz - this is next in your queue after the bugs you were working on

**Comment by Powersource** [comment]
> This settings page should only be visible for rounds in orgs where a special field 'terminology' has been set to True in the database

Would it be bad to give this option to everyone?

> This setting should be per round, and default set on org level.

Could it maybe simply be an org (group) setting?

Although if we'd combine these two suggestions then the group settings page would be a lot more cluttered than it currently is, so in that case would maybe warrant some ui reconsideration.

**Comment by skoteskote** [comment]
@Powersource We decided to not make it available for everyone since the email notification settings is global, so there will be a terminology mismatch there. We'll live with this mismatch for the orgs that require this feature, and deal with it later so we can open this feature to everyone. 

The logic will be more straightforward if its set per round, especially if we take future cases into consideration where users with only a round and no org might want this feature. Defaults is still set on org level.

**Comment by Powersource** [comment]
Fwiw I think both code and ui-wise, just having it on org level would be simpler.

And by adding this feature it feels like we're doing something wrong, I can't think of another app that has this feature. Maybe because I haven't used that many whitelabeled apps. But it plays into the balance of keeping an app developing in one direction and being more opinionated vs trying to make it work for multiple usecases. Maybe I'm overthinking it. Would be interested to hear what Gustav thinks.

**Comment by aerugo** [comment]
We have decided to drop this feature.
