### ISSUE TITLE
[BUG] Data loading slowly, looks like it is missing

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#620]
**Describe the bug**
Across the platform, we are experiencing slow loading times. When data does not load quickly, it sometimes looks as if it is missing. This may confuse users.

**To Reproduce**
When loading a new round, the message 'This round either doesn't exist or you don't have access to it' flickers into view before the round loads, and the 'Sign in' menu is visible, looking as if the user had been signed out. Once or twice I have seen it getting stuck for several seconds. I have also seen this happen with buckets that don't load for a few seconds, instead showing a round as if it had no buckets.

<img width="1438" alt="Screenshot 2022-03-16 at 00 23 11" src="https://user-images.githubusercontent.com/7785081/158488487-0fe31b29-b4bf-4fae-b3f7-cf7be8eea9a4.png">

**Expected behavior**
Data should load more quickly, but at the very least, there should be a loading indicator.

**Browser and device (please complete the following information):**
Tested on Chrome on MacOS.

**Comment by Powersource** [comment]
i'll add a simple loading indicator at least

**Comment by Powersource** [comment]
pushed 339b5963f62db3a7e5faa2d7465b2ffca504a5bc to main

**Comment by tomomiq** [comment]
LGTM
