### ISSUE TITLE
[BUG] Buckets don't show up

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#621]
**Describe the bug**
Sometimes data seems to not load at all without a refresh. This may lead users to worry that their rounds or buckets have been lost. In particular, I have seen this happen with buckets not loading.

**To Reproduce**

This is a little hard to reproduce, but it can be buckets not showing up. [In this round](https://staging.cobudget.com/c/staging) on our staging server, it happens consistently. 

<img width="1551" alt="Screenshot 2022-03-16 at 00 19 33" src="https://user-images.githubusercontent.com/7785081/158488008-cd7e98c2-0743-4482-81a3-20222e2b17df.png">

<img width="767" alt="Screenshot 2022-03-16 at 00 15 32" src="https://user-images.githubusercontent.com/7785081/158487546-459a660a-f464-4544-bedb-f6eed9543153.png">

If I click the About tab, and then go back to Overview, the bucket shows up.

<img width="1551" alt="Screenshot 2022-03-16 at 00 19 43" src="https://user-images.githubusercontent.com/7785081/158488016-2b3a7d03-2da5-48b0-8fe3-513492b2e832.png">

Error log attached, including full JSON response for the GraphQLError:
[staging.cobudget.com-1647386079359.log](https://github.com/cobudget/cobudget/files/8257806/staging.cobudget.com-1647386079359.log)

**Comment by gustavlrsn** [comment]
Just fixed this on staging.
