### ISSUE TITLE
[BUG] User received 7 emails for one 'bucket published' event

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#622]
Fran said a user ran into this.

**Comment by Powersource** [comment]
checked the db, i found 4 user accounts that looked like they could be the same person but Fran says it's actually just two guys with the same name. So he has 2 accounts so might be getting double mailed for that, but that's not enough for 7 to arrive.

**Comment by gustavlrsn** [comment]
@aerugo @Powersource - yes, if you DM me the email I can check the logs

**Comment by gustavlrsn** [comment]
Yeah, looks like quite a few bucket published emails have been sent
<img width="868" alt="Skärmavbild 2022-03-17 kl  11 42 19" src="https://user-images.githubusercontent.com/1552194/158792742-6ab9466f-fccf-4113-94db-aedd2a957024.png">

**Comment by Powersource** [comment]
That the emails aren't sent within seconds of eachother makes me think it's not a bug in `ui/server/services/EmailService/email.service.ts`.

The 'bucket published' emails look exactly the same within the same round at the moment, maybe things would feel less spammy if the emails actually clarified that they're notifying about different buckets? This is the current implementation:

```
      subject: `There is a new bucket in ${event.title}!`,
      html: `Creativity is flowing in ${escape(
        event.title
      )}! <a href="${collLink}">Have a look at the new buckets in this collection.</a>
      <br/><br/>
      ${footer}
      `,
```

**Comment by aerugo** [comment]
I really think that we might not want to notify about new buckets by default… For big rounds like the Borderland, it would mean sending 200+ emails each of 1000+ users during a period of only a few weeks.

**Comment by Powersource** [comment]
Fix is on staging, testing tracked in this other issue https://github.com/cobudget/cobudget/issues/702
