### ISSUE TITLE
[BUG] Transaction list broken

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#623]
**Describe the bug**
Transaction list is currently broken, shows:

'Application error: a client-side exception has occurred (see the browser console for more information).'

**To Reproduce**
As round member, go to `https://staging.cobudget.com/c/[YOUR ROUND]/transactions`

**Comment by gustavlrsn** [comment]
Fixed in 58f889249936d2007fc4feaa3a737e616d06bd7e
