### ISSUE TITLE
Admin ocassionally needs to be able to edit contributor allocations during rounds. 

### ISSUE THREAD

**Issue by getresults** [cobudget/cobudget#63]
I'm getting requests for users to do allocations on their behalf for various reasons (they don't have internet access where they are, they've made a mistake and have asked for it to be corrected etc.) 

As an admin I would like the ability to switch to a specific user so I can edit / adjust their allocations. 

A "switch to user" link that temporarily switches to a specific user would be great (with a matching link to switch back to admin).

**Comment by derekrazo** [comment]
I don't see it as a given that this should exist. Admins can't change people's votes in Loomio. It's not the admin's job to do everything, and if people have limited internet / want to change allocations that is separate from the specifics of this proposed solution.

**Comment by derekrazo** [comment]
I've reopened this as a question about editing contributions.

**Comment by getresults** [comment]
@derekrazo - the intent of this issue was not to edit contributor allocations after the round closes but to provide occasional assistance **during** rounds for contributors having difficulty gaining access.  Once a round is closed I would consider figures final.
