### ISSUE TITLE
[FEATURE] (copy "bug") "Join round" should be "Request to join round" 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#630]
**Describe the bug**

UI copy does not match what's actually happening - 

Non-member user thinks they are doing "Join round" and automatically joining but actually they are only requesting to join and require approval before anything happens. 

**To Reproduce**

Go to a Round page of which you are not a member 

![image_2022-03-18_11-54-08](https://user-images.githubusercontent.com/1287179/158990891-faf1bff9-f1c6-4d4f-bcd7-9609119ce0e5.png)

![image_2022-03-18_11-54-47](https://user-images.githubusercontent.com/1287179/158990641-bb819c26-6892-4a20-9bad-161003b064ad.png)

**Expected behavior**

Copy should be 

* Button: Request to join round. 
* Flash notification: Your request has been sent.

**Comment by Powersource** [comment]
This should be the current copy on a request-to-join round. Are you sure it was a round like that and not an Open round?

**Comment by tomomiq** [comment]
I can't check (not an admin) but I remember that there was no "create bucket" button appearing after Fran got "You joined this round".

**Comment by tomomiq** [comment]
Confirming that this is a bug as reported.

**Comment by francesca-sp** [comment]
looks good!
