### ISSUE TITLE
[BUG] Cannot save group icon file (staging)

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#635]
fyi bucket images work, so it seems to be just for the group icon 

**To Reproduce**

1. Create a new group 
2. Upload image file 
3. Nothing happens 

**Expected behavior**
For the file to be uploaded and a preview to be displayed on the page 
OR some kind of error message so the user knows to try something else 

Here are the files that we tried to upload: 

<img width="392" alt="Screenshot 2022-03-22 at 13 46 54" src="https://user-images.githubusercontent.com/1287179/159501198-c749ce15-763c-4018-b08a-055dd30c5f9d.png">

<img width="166" alt="Screenshot 2022-03-22 at 13 43 39" src="https://user-images.githubusercontent.com/1287179/159501204-96f76eb5-64f6-4085-9787-facea398e8d3.png">

![test](https://user-images.githubusercontent.com/1287179/159501194-f1e7c944-1416-4fb8-bc8c-9f908f6cfc4b.png)

![test](https://user-images.githubusercontent.com/1287179/159501544-e97b4d34-ad99-430b-b932-8ed5e3436795.jpeg)

**Comment by eden-gt** [comment]
it's working! thank you
