### ISSUE TITLE
[BUG] Cannot create a new round for a group (only on staging)

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#636]
**Describe the bug**

If I try to create a new round for a group that I'm an admin of, I get this page: 

<img width="1112" alt="Screenshot 2022-03-22 at 14 14 18" src="https://user-images.githubusercontent.com/1287179/159502462-ef39f669-d73c-4f20-ac65-be05f718cc11.png">

**Expected behavior**

To get the form to create a new round.

**Comment by Powersource** [comment]
should be fixed by 41c0fd87b3cbf4ae242df12c73f635178889de6d now
