### ISSUE TITLE
Personal / Group allocation summaries reversed + mouse over help.

### ISSUE THREAD

**Issue by getresults** [cobudget/cobudget#64]
On the Buckets screen are the "Your Funds" and "Group Funds" formats reversed? 

i.e.: 

"Your Funds"  shows  **$personal funds left to allocate** / $available funds to allocate. 

"Group Funds" shows  **$group funds already allocated** / $total group funds. 

It would make more sense if these were consistent with "Group Funds" showing funds to allocate/total group funds. 

Additionally it would be great to have mouse over descriptions for each of these as it's not immediately obvious to new users. 

[Originally suggested by Jessy]

**Comment by derekrazo** [comment]
Awesome point. We went back and forth on this a bit. Labeling the need for user testing.
