### ISSUE TITLE
[BUG] Review feature is not working

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#651]
**Describe the bug**
When clicking on the "review" button, there is an error message.

**To Reproduce**

1. Go to a round in which the review feature is activated. 
2. Go to any bucket in that round which has been published and is open for funding
3. Click on 'review'
4. See error, see screenshot
![image](https://user-images.githubusercontent.com/3641828/160639936-f2abf1be-86fd-4c50-98ae-ad303f5ca113.png)

**Comment by Powersource** [comment]
fixed in 93ec655b , should be up on staging in a few minutes

**Comment by tomomiq** [comment]
LGTM

<img width="1365" alt="Screenshot 2022-04-04 at 21 56 06" src="https://user-images.githubusercontent.com/1287179/161621685-e0fb6500-9e53-42ab-9249-acfb4b59f5f8.png">
