### ISSUE TITLE
[BUG] cannot delete round 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#655]
**Describe the bug**

I get an error that stops me from deleting a round. 

**To Reproduce**

1. Go to a round's Setting page 
2. Scroll down to the Danger Zone  
3. Type the text and click "delete this round" 
4. Get this error 

<img width="1213" alt="Screenshot 2022-03-31 at 17 37 21" src="https://user-images.githubusercontent.com/1287179/161094534-82c9c752-8f78-43bd-a110-f822ec11e592.png">

**Expected behavior**

The round is successfully deleted.

**Comment by Powersource** [comment]
It seems the round actually got deleted but this error made the ui act up, fixed now.

Also found some security issues, such as people accessing the api being able to delete rounds as long as they're logged in, also fixed.

**Comment by tomomiq** [comment]
I was able to delete a round.
