### ISSUE TITLE
[FEATURE] stop me from commenting (when I don't have the rights) instead of throwing a GraphQL error

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#656]
**Describe the feature**

On a bucket that belongs to a round that I am not a member of, it looks like I can comment (I get the WYSWYG) but actually I can't - and I find out by getting a GraphQL error. 

Proposal: If I am not allowed to comment, the WYSWYG is not visible to me + the message "You must be a member of this round to add a comment." 

<img width="1213" alt="Screenshot 2022-03-31 at 17 29 31" src="https://user-images.githubusercontent.com/1287179/161092884-f18cd42e-7c5c-4000-961a-fac2e137d094.png">

**Comment by Powersource** [comment]
We were checking if the user either *is a member* or *has been a member* so I'm guessing your user had been removed. Fixed the logic now in 205c1876 , should be up on staging in a few minutes

**Comment by tomomiq** [comment]
LGTM 

<img width="1394" alt="Screenshot 2022-04-04 at 19 42 32" src="https://user-images.githubusercontent.com/1287179/161600958-3c681bb5-cf4f-4a4f-97cf-e647851debf3.png">
