### ISSUE TITLE
[FEATURE] re-direct to the last visited Org page after logging in 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#666]
**Describe the feature**

Currently, if you are part of multiple organizations or SoloRounds, you are taken to this page after logging in - which is confusing.   
How about if you get re-directed to the Org Top (or SoloRound page) of whatever page you were last on? And if you just created your account, re-direct to /new-round. 

<img width="1365" alt="Screenshot 2022-04-04 at 22 24 33" src="https://user-images.githubusercontent.com/1287179/161626147-be4561b4-1a9b-4525-bebc-5a9a7bae568a.png">

**Comment by alinauroz** [comment]
Should we save users last active page and update it on every page load?

**Comment by aerugo** [comment]
Yes, I guess we can do that. In a cookie, I guess? Not need to save it in the database, I think.

**Comment by skoteskote** [comment]
If we do it in a cookie and we want to save it after the user session we need cookie approval banner and policy.

**Comment by gustavlrsn** [comment]
I think a common approach is to save the redirect path in a query parameter in the URL

**Comment by gustavlrsn** [comment]
Basically take the url you were on before clicking Login

**Comment by alinauroz** [comment]
> I think a common approach is to save the redirect path in a query parameter in the redirect URI

I add a `r` param in url to redirect. 

But for example when a user has closed browser and he opens the website again (cobudget.com), we do not know the where he was last time.

**Comment by aerugo** [comment]
@alinauroz - can you describe a case where we need to know where a user was before they closed a browser window?

**Comment by alinauroz** [comment]
> @alinauroz - can you describe a case where we need to know where a user was before they closed a browser window?

Im saving the latest page's pathname in localStorage every-time a user visits any page on cobudget and if user is logged in.

**Comment by aerugo** [comment]
I understand. But this is my question:
When do we need that? What is the user story when we need to remember where a user was if they close their browser, instead of just storing the redirect path in a url parameter like Gustav suggests?

I am asking these clarifying questions to understand if you might have thought of some user story where this is needed, that I might not be aware of.

**Comment by alinauroz** [comment]
> I understand. But this is my question: When do we need that? What is the user story when we need to remember where a user was if they close their browser, instead of just storing the redirect path in a url parameter like Gustav suggests?
> 
> I am asking these clarifying questions to understand if you might have thought of some user story where this is needed, that I might not be aware of.

@tomomiq said it was confusing for users because they were taken to homepage after log in. So if a user is logging in on cobudget.com/signin, we do not know on which page the user was last time because there is not redirect query param in url.

**Comment by alinauroz** [comment]
@gustavlrsn you are suggesting following, right?

When a user logs out we direct user to `cobudget.com?r=<last_visited_page>` and when he logs in we take user to the last visited page?

**Comment by gustavlrsn** [comment]
@alinauroz pretty much that, yes

**Comment by Powersource** [comment]
Also merged https://github.com/cobudget/cobudget/pull/695 so should also work when logging in with fb

**Comment by francesca-sp** [comment]
Maybe we're not testing this correctly, but Elena and I both cannot seem to get this to work as expected. Could someone tell us in more detail what would need to be done to test this? 
What we have done so far is on staging, login, go to a certain group, then logout while on that group page, and then login again. When we both do that, we don't get sent back to the group page, but instead end up on the landing page as before. Is this what we should be testing for, or did we get it wrong? @Powersource

**Comment by Powersource** [comment]
Sorry, maybe should have clarified, the way we ended up doing it (maybe
decided in chat) was:

* Go to a page while logged out, eg a bucket
* Log in
* End up back on the same page you were on before

**Comment by tomomiq** [comment]
hi @Powersource Is this on staging? I always end up on the landing page.

**Comment by Powersource** [comment]
@tomomiq It seems to work for me both on staging and in production

**Comment by Powersource** [comment]
Both in firefox and chrome

**Comment by Powersource** [comment]
https://www.loom.com/share/775bc6e9880f4d5aa70e1ad48a17c011
