### ISSUE TITLE
[FEATURE] Set up new google sign-in client for cobudget

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#671]
When setting up sign-in with google I kept things simple and reused our client keys that we used for the old plato project app deployments. But that caused the log in screen for google to tell the user to log into "Plato project" not Cobudget, and to use the wrong logo https://github.com/cobudget/cobudget/issues/611#issuecomment-1087979337 I requested to change the logo and name, but now I got this email

> Hi,
> --
> Thanks for your patience while we reviewed your project. Your project plato-project has multiple unique domains in the redirect URI and origin URLs, many of which have unrelated applications. This is in direct violation of the Google API Services: User Data Policy,  which requires that projects accurately represent their identity and  intent to Google and to our users when they request access to Google  user data. Please follow the instructions on the Google API Console to:  Create new projects Migrate your redirect URIs with distinct brands to different projects, and/or Ensure that these projects accurately represent their true identity to Google users  You can find more information in the OAuth Application Verification FAQ.  To make sure we don't miss your messages, respond directly to this email to continue with the verification process.
> 
> Hi,
> 
> Thanks for your patience while we reviewed your project.
> 
> Your project plato-project has multiple unique domains in the redirect URI and origin URLs, many of which have [unrelated applications](https://support.google.com/cloud/answer/7650096?hl=en&ref_topic=3473162). This is in direct violation of the [Google API Services: User Data Policy](http://developers.google.com/terms/api-services-user-data-policy), which requires that projects accurately represent their identity and intent to Google and to our users when they request access to Google user data.
> 
> Please follow the instructions on the [Google API Console](http://console.developers.google.com/) to:
> 
>     Create new projects
>     Migrate your redirect URIs with distinct brands to different projects, and/or
>     Ensure that these projects accurately represent their true identity to Google users
> 
> You can find more information in the [OAuth Application Verification FAQ](https://support.google.com/cloud/answer/9110914).  To make sure we don't miss your messages, respond directly to this email to continue with the verification process.

I think the best solution is to revert this client to simply Plato project and to create a new google client for cobudget. This might take a few weeks though where we wouldn't be able to log in with google on cobudget, but I think it hasn't hit production yet so no one's used to it yet.

**Comment by Powersource** [comment]
I've removed the google env vars from staging and prod now so the sign in with google button shouldn't appear while we're making changes

**Comment by Powersource** [comment]
> Push to production?
> 
> Your app will be available to any user with a Google Account.
> 
> You've configured your app in a way that requires[ verification](https://support.google.com/cloud/answer/9110914). To complete verification, you will need to provide:
> 
>     An official link to your app's Privacy Policy
>     A YouTube video showing how you plan to use the Google user data you get from scopes
>     A written explanation telling Google why you need access to sensitive and/or restricted user data
>     All your domains verified in Google Search Console

x_x

Although I think we've gotten past this before and not have to make a youtube video

**Comment by Powersource** [comment]
I think I've set up everything correctly now. Now we wait (for approval by google)

**Comment by tomomiq** [comment]
I assume this is related to this in-progress status of this feature but fyi I get this error on staging. weirdly, if I reload, I am logged in.

<img width="1192" alt="Screenshot 2022-04-06 at 22 59 28" src="https://user-images.githubusercontent.com/1287179/162070168-c41bcd93-a3bd-415f-874f-ef5682418d76.png">

**Comment by Powersource** [comment]
Yeah i think this will go away once staging is redeployed or we deploy to prod again. Or more specifically, the log in with google button should disappear.

**Comment by Powersource** [comment]
![image](https://user-images.githubusercontent.com/1427063/162801539-372bd823-d541-4de6-9f15-17ec25aa48db.png)

![image](https://user-images.githubusercontent.com/1427063/162801625-229e3cb1-1a4c-4599-9066-260d08f1454f.png)

![image](https://user-images.githubusercontent.com/1427063/162801650-2a7dde1c-0108-47ac-9c7e-dcb8ec660b0f.png)

![image](https://user-images.githubusercontent.com/1427063/162801677-c91a3acf-52d1-4542-9417-32c548013845.png)

**Comment by Powersource** [comment]
Really tired of google right now

**Comment by Powersource** [comment]
@tomomiq can you look at fixing this?

**Comment by Powersource** [comment]
We're back at it. I think the only thing we're not complying with is the branding, I think we need to add the google logo on the login button. I'll do that now.

![image](https://user-images.githubusercontent.com/1427063/169530103-7fc3cf93-8c23-4296-b6df-65d729577f40.png)
![image](https://user-images.githubusercontent.com/1427063/169530161-a87c1f4b-910f-46f3-8cb2-b028f251f550.png)

**Comment by Powersource** [comment]
It sounds like we're approved now!
