### ISSUE TITLE
[FEATURE] Toggle direct funding to bucket

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#674]
![image](https://user-images.githubusercontent.com/7785081/162047607-df16924e-af38-4dd7-b850-914365a3cbbd.png)

- Add Direct funding as another field in the bucket edit view
- Before the bucket can accept direct funding, a bucket co-creator or admin must click the Direct funding row. They get shown the direct funding terms set by the round admin and select if the funds are a donation or a transaction.
- If the funding is a transaction, the bucket co-creator must set a description and VAT, and can set an optional minimum contribution.

**Comment by Powersource** [comment]
@aerugo @tomomiq Some clarifying questions

As soon as the cocreator clicks "+ Direct funding", there should be no disabling of it?

Are we safe to hide the VAT field on donations, e.g. skimming here https://www.familjensjurist.se/fraga-juristen/ovrigtannat/nar-ar-donationer-skattefria/ "Om donationerna sker i samband eller i syfte att du ska kunna hålla i en föreläsning kommer donationerna troligtvis inte att betraktas som gåvor och således blir du skatteskyldig för donationerna.", thinking about the borderland here, the donor doesn't get anything directly but something is definitely directly depending on the money coming in. Maybe it's tax free in most cases but enough cases have taxes that we still want to provide the option to users?

**Comment by aerugo** [comment]
> As soon as the cocreator clicks "+ Direct funding", there should be no disabling of it?

Hmm, why not? I guess they could just connect to Stripe again - to the account they created the first time.

> Maybe it's tax free in most cases but enough cases have taxes that we still want to provide the option to users?

If what they are doing is not covered as a tax free donation, they would simply need to make the funding a transaction. 
There is no such thing as a taxed donation - it is rather that if you give money to someone in certain contexts, it is not a donation but a transaction. But making this call is up to the users, especially since there will be different laws in every country.

**Comment by Powersource** [comment]
> Hmm, why not?

I see nothing in the ui sketch for it. But I could improvise something.

**Comment by aerugo** [comment]
No, I think @tomomiq and I simply didn't think of it. Thanks for the catch @Powersource!

**Comment by Powersource** [comment]
Also clarification: This section should only be shown to admins/cocreators of the bucket right? Normal users will only receive this information when they click Fund in the upper right.

**Comment by Powersource** [comment]
PR merged into integration branch

**Comment by tomomiq** [comment]
Remaining work is https://github.com/cobudget/cobudget/issues/785 but closing this one.
