### ISSUE TITLE
[FEATURE] Toggle on and off admin specific notifications 

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#683]
Add a section to the user email notification management section that shows admin specific notifications. 

This section only appears if you are an admin. For now, the first notification email toggle to add is: 
* A user requests to join a round

This turns on and off the emails that are sent when a user requests to join a group.

**Comment by alinauroz** [comment]
Email settings are general. By general I mean they are not group or round specific. So, this settings will only appear if a user is an admin of at-least one round.

*What should happen in the following edge case?*
*A user is an admin of round and changes admin email settings. Later, he is no more an admin of any round and he wants to change/revert admin email settings.*

**Comment by aerugo** [comment]
Good point @alinauroz. 

@francesca-sp - before we implement this we will need to look into round and group specific notifications.

**Comment by francesca-sp** [comment]
Tested and is working as expected. At a later date we can do a bit of design work on the notifications page, but that seems out of scope for now.
