### ISSUE TITLE
[FEATURE] Log in with password

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#701]
**Describe the feature**
A user should be able to log in with a password + username (or email). This is a request from Malmö Tillsammans, but I have also noticed that this will become an issue. 

Currently, the only option to log in is via Facebook or magic link. For users who do not have their account tied to Facebook this makes it hard for them to log in on devices other than their own. 

See the following use case: 
* I am in presenting the platform to a group of people, in the context of eg a workshop. 
* For this presentation, I'm using a public computer that is not mine, hooked up to a projector, as is often the case on conferences, etc. 
* My account is not tied to Facebook, so my only option is to log in through magic link.
* The magic link is sent to my email, which I only have access to on my personal computer or device. 
* I then need to transfer the magic link from my device to the public computer. (there's of course a bunch of workarounds here, involving airdrop or opening your mail on the public computer, but they all constitute a pretty bad UX, especially when I'm presenting something.)

**Comment by aerugo** [comment]
I think we will probably not implement this anytime soon. 
Keeping track of usernames and passwords requires a different auth infrastructure. 
OpenCollective and many other platforms have switched to only using magic links for that very reason.

**Comment by skoteskote** [comment]
How do you solve the above mentioned use-case?

**Comment by skoteskote** [comment]
Is it possible to use the verification code as a temporary password?

**Comment by aerugo** [comment]
You prepare ahead of time and ask the organizers to let you log yourself in on their computer before the presentations start, opening your email on their computer while it is not connected to the projector.

A slightly cumbersome tradeoff that enables better data security and less info-sec overhead.

**Comment by skoteskote** [comment]
That is a really bad UX. How about using the verification code, or similar, as a temporary password?

**Comment by aerugo** [comment]
> How about using the verification code, or similar, as a temporary password?

Perhaps, but I suppose that it would then be an alternative login flow, as most users would become confused about the idea of a temporary password. I suppose that there could be a "hidden" login page like "cobudget.com/login-password" where one might login with the verification code, which would be deactivated after the first login or after a certain amount of time.

However, this is a feature that would take a couple of weeks to develop, test, and deploy. And the target user group for this UX is very narrow: People who want to showcase the platform to a group during a conference where they are not using their own computer. And a number of workarounds for this use case exist, so this feature is about making it smooth and convenient for this narrow use case.

My assumption is that there is quite a long list of features we should prioritize above this that either affect more users or affect users in ways that are not possible to work around. I am open to changing my mind though if there are things I have not taken into account!

**Comment by skoteskote** [comment]
The use case is a lot more common than conferences - It covers basically any process where I have a group of people participating in a workshop, and where the workshop shows them what is happening on a screen. This is the use-case for almost all workshops MT has done and will be doing. 

However, using the platform for workshops might be quite specific to the MT use case, so if we don't foresee the platform to be used for workshops in any other contexts then it might not be that important. 

Of course, if it's not possible it's not possible. But IMO this makes our platform look quite beta, as the feature of logging in with a password is pretty standard for all other existing platforms. I am personally not using any other tool/platform that is missing this feature.

**Comment by skoteskote** [comment]
Just to clarify - I'm posting this issue since MT emailed me and asked for the possibility to reenable the "login with password" feature, as they had it in the old platform.

**Comment by skoteskote** [comment]
Closing this for now as we will not implement it.
