### ISSUE TITLE
[FEATURE] "A new bucket is published" default to off in email notifications

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#702]
**Describe the feature**
The "A new bucket is published" toggle should be off by default in email notifications. The email notifications becomes very spammy when it is on and the platform is used for a workshop. 

Context: MT recently did a workshop where 30 ideas were added during the course of 30 minutes. Each user subsequently got 30 emails informing them of this, leading to a bad first experience with the otherwise very useful email notifications feature.

**Comment by Powersource** [comment]
related https://github.com/cobudget/cobudget/issues/622

**Comment by Powersource** [comment]
This is on staging now

**Comment by Powersource** [comment]
It will be off for new users, including users who haven't visited their email settings page

**Comment by francesca-sp** [comment]
tested, and works correctly!
