### ISSUE TITLE
[FEATURE] Activity / Metrics Dashboard 

### ISSUE THREAD

**Issue by DavidsBees** [cobudget/cobudget#707]
A place for the cobudget team to get an overview of cobudget metrics/analytics, where data is pulled together to see them in one place. This serves the need to be able to see how cobudget is used in order to make more informed decisions. 

Specifications in detail here (+ screenshots of legacy version):
https://docs.google.com/document/d/1wAY0t3Gq0L-OhOzHLf_YNpEO2VM6oUo0Vo1Vn4oBc_g/edit

**Comment by aerugo** [comment]
We will use Metabase.
