### ISSUE TITLE
Member gets emailed when round is about to close

### ISSUE THREAD

**Issue by jonlemmon** [cobudget/cobudget#71]

**Comment by derekrazo** [comment]
Notes from planning meeting -

Check - can buckets be proposed by people?

If you create a around and allow buckets to be proposed - emails go out when round

__States :__
Pending -> proposals -> contributions -> close

**Comment by derekrazo** [comment]
@jonlemmon - could you give us an estimate on this one plzzzz? thanks!

**Comment by jonlemmon** [comment]
@derekrazo I'll say 2 since it requires setting up a cron job (something we haven't done before on this project).
