### ISSUE TITLE
[BUG] Selector list styling is influenced by landing page css

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#713]
**Describe the bug**
The styling of the groups in the `<Selector />` list is off, with a smaller font size and maybe the wrong color, but only on the landing page, so I suspect the css from the Webflow landing page is causing it. 

<img width="396" alt="image" src="https://user-images.githubusercontent.com/1552194/167409127-f3f48d6d-9783-45fc-a899-bd0276ec035b.png">

**Comment by francesca-sp** [comment]
All rounds and orgs have the same font and color now on the main landing page as on the subpages, so it seems to be working.
