### ISSUE TITLE
Admin opens round from pending state

### ISSUE THREAD

**Issue by ahdinosaur** [cobudget/cobudget#73]
TODO:
- [] design and user testing

### admin creates round

- modal with name and `membersCanProposeBuckets` setting
- round is created in pending state
  - [1] \(API) non-admins cannot see pending rounds

### admin opens round for bucket creation

- only if `membersCanProposeBuckets` is set
- [2] \(UI) admin chooses date to start contributing and date to end round
  - add string `state` to Round model
  - [1] \(API) create `/rounds/:id/actions/start` that takes in `contributionDate` and `endDate` if `membersCanProposeBuckets`
  - change round to `proposal` state
  - [1] \(API) email members about bucket proposals
- [1] \(API) when date to start contributing happens
  - round changes to contribution state
  - email members about bucket contributions
- [1] \(API) when date to end round happens
  - round changes to closed state

### admin opens round for bucket contributions

- only if `membersCanProposeBuckets` is not set
- admin chooses date to end round
  - create `/rounds/:id/actions/start` that takes in `endDate` if not `membersCanProposeBuckets`
  - change round to `contribution` state
  - email members about bucket contributions
- when date to end round happens
  - round changes to closed state

**Comment by ahdinosaur** [comment]
@euglazer

**Comment by euglazer** [comment]
on itttt
