### ISSUE TITLE
[FEATURE] Add "experimental features" bool to orgs

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#731]
We want to give some orgs access to experimental features.
This is toggled by a bool set in the database.

Direct funding is the first such feature.

**Comment by Powersource** [comment]
Should we hide the features just on an UI level or also block access to them in the API? The former would be simpler.

**Comment by aerugo** [comment]
Just hide on an UI level. If people do it through the API they are clearly determined and should know the risks

**Comment by tomomiq** [comment]
Can you propose a way to test this @Powersource @aerugo or close the issue — thanks!

**Comment by Powersource** [comment]
@tomomiq the org on staging that we're currently testing direct funding in should have direct funding enabled. but if you create a new org then that org shouldn't have those features enabled.

**Comment by tomomiq** [comment]
I see. The "create new org" doesn't work yet (get a blank page) so this testing is still in progress. Reminder to myself: https://staging.cobudget.com/tomomitest

**Comment by francesca-sp** [comment]
The above still applies, this cannot be tested yet because creating groups is broken.

**Comment by eden-gt** [comment]
Create new group is working now, we've created this one: https://staging.cobudget.com/test-abc
We are not seeing the experimental features warning in settings, so think this is working!
