### ISSUE TITLE
[BUG] Goal and stretch goal have different number formats

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#734]
<img width="977" alt="Screenshot 2022-05-30 at 16 20 17" src="https://user-images.githubusercontent.com/7785081/171011441-917d28fe-ce5d-44bc-927e-d2b4f732e058.png">

Change so that both use the same format. For now we are not setting format according to currency, so let's just use whitespace as a thousands divider and round of the decimals, like 12 000 instead of 12,000.00.

**Comment by Powersource** [comment]
I'm guessing that this is introduced by the new localization. For some numbers we now localize them according to language settings (e.g. india has different thousand dividers than us). I suggest we format both numbers using the localization library.
