### ISSUE TITLE
[BUG] Link to guide in emails is dead

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#737]
We are linking to guide.cobudget.co, should it be guide.cobudget.com?

**Comment by aerugo** [comment]
No, it should be https://cobudget.helpscoutdocs.com/ - the resource David just finished putting online.

**Comment by gustavlrsn** [comment]
Looks like it is possible to set up [custom domains in helpscout](https://docs.helpscout.com/article/1423-customize-your-docs-site), maybe we should point `guide.cobudget.com` or `docs.cobudget.com` to that page?

**Comment by Powersource** [comment]
I think i fixed this a few days ago
