### ISSUE TITLE
[BUG] All kinds of characters in usernames

### ISSUE THREAD

**Issue by gustavlrsn** [cobudget/cobudget#738]
**Describe the bug**
You can basically set your username to anything you want, including spaces, funky characters and what not.

The username should ideally be something simple to type (for the @at functionality etc) and be URL-friendly.

**Suggestion of fix**
- [x] Allow `A-z` `0-9` `-`, (maybe `.`?) and no special characters. Make sure we have case insensitive uniqueness.
- [x] When we check if a user has a username (and open the "complete signup" modal), we can also check if they have a bad username and ask them to fix it, showing a different modal or at least a different wording.

This will also fix the issue of emails as usernames form Keycloak.

**Comment by Powersource** [comment]
This is a good fix. In the future would be nice to allow non-latin names as well.

**Comment by tomomiq** [comment]
LGTM!
