### ISSUE TITLE
[FEATURE] Add progress bar to languages

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#744]
We should add translation completeness progress bars to the languages, like on OpenCollective. Right now it feels buggy as  choosing a translation with only a few strings translated usually has no visible effect.

**Comment by DavidsBees** [comment]
I cant find that progress bar - I see the translations here so far: 
![image](https://user-images.githubusercontent.com/80971095/177329939-f49851d2-a3d3-4fda-8eec-79313640af01.png)

**Comment by Powersource** [comment]
Yeah this isn't merged to far so it's just been tagged wrong

**Comment by Powersource** [comment]
If the relevant env vars are missing (they were on staging and prod, i've added them now. they're still missing on the custom domain deployments) then the progress shows as 0%. In that case it's better to hide the percentage.
