### ISSUE TITLE
[FEATURE] When going "back" to bucket list from bucket, got to same page 

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#747]
As people explore different buckets to fund, a likely behaviour will be to open buckets and then press "back" to find other buckets. Currently, this means that you do not end up on the same page as you were, and you need to scroll through again. This is especially annoying in large rounds, like the Borderland. 

We should save the page position for the user so they can navigate back to where they were in the bucket list.

**Comment by gustavlrsn** [comment]
Maybe a query variable `pages` that keeps track of the number of pages you have loaded should be enough, I think Next.js will keep track of scroll position beyond that. So that from the second page you would have the url look like: `https://cobudget.com/c/your-round?pages=2`

**Comment by Powersource** [comment]
Shouldn't urql automatically grab the data from the cache? It used to I think. Feels like we accidentally clear it somehow.

**Comment by gustavlrsn** [comment]
It does but the number of pages loaded is a local state on the bucket page list, which is reset when the page is unmounted, so it should just be a matter of preserving that and then the urql cache will do the rest.

**Comment by Powersource** [comment]
Hmm ok so I guess this is one of the drawbacks of this pagination strategy

**Comment by DavidsBees** [comment]
It is not working reliably - i get randomly put back to the same location on the page OR at the top of the page. This seems to be independent from the bucket or its location on the page

**Comment by aerugo** [comment]
@alinauroz - see comment from @DavidsBees
