### ISSUE TITLE
[BUG] Bucket review possible even though its turned off

### ISSUE THREAD

**Issue by DavidsBees** [cobudget/cobudget#751]
**Describe the bug**
The bucket review feature is turned off in the round settings. Yet, the review button appears in the buckets

**To Reproduce**

1. Go to 'Round Settings'
2. Click on 'Show Review Prompt : False'
3. Go to any bucket

**Expected behavior**
No review button once the feature is turned off

**Comment by Powersource** [comment]
Please link the round

**Comment by alinauroz** [comment]
@aerugo should it be considered a bug. I think we discussed that review button should always be there for admins.

If review option is turned off, admins can still review. Users other than admins, can not review in this case.

**Comment by aerugo** [comment]
For now, let’s turn off the review button for everyone when review is disabled. I think it’s too confusing to explain that it’s always on for admins - let’s keep it simple for now.
