### ISSUE TITLE
[BUG] Strech goal miscalculation 

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#752]
Something goes wrong sometimes with the stretch goal calculation. 

See this bucket: https://dreams.theborderland.se/c/borderland-dreams-2022/cl3ovu3xm182909kyyeaz76t6

![](https://media.discordapp.net/attachments/884799416005984306/982585202385756200/image0.jpg)

**Comment by eden-gt** [comment]
We've tested this in two rounds within GT-Testing (group), in both EUR and SEK and it's working totally fine in those.
