### ISSUE TITLE
[BUG] Certain rounds on staging load unreliably 

### ISSUE THREAD

**Issue by aerugo** [cobudget/cobudget#782]
At least one round (https://staging.cobudget.com/c/staging-round) is not loading reliably on staging. See behaviour:

https://user-images.githubusercontent.com/7785081/176889548-3dad4bb6-e00f-41f2-b4cd-49663b08310a.mov

<img width="800" alt="Screenshot 2022-07-01 at 11 54 58" src="https://user-images.githubusercontent.com/7785081/176889723-7379cb61-7898-4c0b-811f-258c06744a61.png">

**Comment by alinauroz** [comment]
Issue can be reproduced by removing yourself as admin and reloading the page.

**Comment by francesca-sp** [comment]
it looks like it's working correctly now!
