### ISSUE TITLE
[BUG] Filtering of buckets not working

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#791]
**Describe the bug**
I was looking through the buckets on the Grassroots fund page: https://cobudget.com/grassrootsfund/swiss-grassroots-fund-for-the-climate?f=COMPLETED

And selected the filter to only show "delivered" buckets. However, the filter does not seem to work, it is still showing all buckets. 

**To Reproduce**

1. Go to 'https://cobudget.com/grassrootsfund/swiss-grassroots-fund-for-the-climate'
2. Select the filter to only show 'delivered'
3. Scroll down and you will see more than 7 buckets (which is the number that should be showing)

**Expected behavior**
The buckets that do not have the status "Delivered" should no longer show up. 

**Screenshots**
![image](https://user-images.githubusercontent.com/3641828/178229040-69946900-3961-4920-a9f8-914dd206ecf9.png)

![image](https://user-images.githubusercontent.com/3641828/178229099-ffe53f05-524d-4665-b410-cd6af653226b.png)

**Comment by eden-gt** [comment]
it's working now!
