### ISSUE TITLE
[BUG] When selecting filters, page jumps

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#792]
**Describe the bug**
When selecting and unselecting filters by status, the page always jumps to the top automatically. This is especially annoying if the page has a big header with an image, since you have to scroll down again each time. 

**To Reproduce**

1. Go to any round with various buckets in it in different stages
2. Select and unselect filters
3. You will see that each time you click on of the filters, the page jumps to the top immediately

**Expected behavior**
I expect to stay on the same place on the page when I am selecting and unselecting filters.

**Comment by alinauroz** [comment]
It's fix is quick. I assigned it to myself.
