### ISSUE TITLE
[BUG] Bucket creation date always shows todays´ date

### ISSUE THREAD

**Issue by DavidsBees** [cobudget/cobudget#793]
In the bucket detail page the date shown for bucket creation seems to update always to todays date

**Expected behavior**
Time stamp with the actual bucket creation

**Screenshots**
![image](https://user-images.githubusercontent.com/80971095/178490409-2e66c198-e245-49c1-a726-a48f0e849c2e.png)

**Comment by tomomiq** [comment]
LGTM.
