### ISSUE TITLE
[MINOR] New link in emails to docs

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#798]
from @DavidsBees 

> The custom domain to helpscout docs is now setup with guide.cobudget.com
>
> Could you change that in the email / notification links

**Comment by DavidsBees** [comment]
Hi @alinauroz , it still shows guide.cobudget.co  

[Discover how it works.](https://guide.cobudget.co/))

**Comment by DavidsBees** [comment]
Sorry @alinauroz , i realized i wasnt on staging. Just reviewed there - of course its working 😆
