### ISSUE TITLE
[BUG] : Page crashes after inviting members to group

### ISSUE THREAD

**Issue by alinauroz** [cobudget/cobudget#803]
Page crashes after inviting members to group.

**To Reproduce**
1. Open group members page
2. Invite members by email

**Expected behavior**
A user should see a success message

**Screenshots**

https://user-images.githubusercontent.com/38759611/181878046-d74b1c7e-5bad-4ae6-82a7-0b70322baea0.mov

**Comment by DavidsBees** [comment]
Works now, thanks!
