### ISSUE TITLE
[BUG] Payment goes through but does not show up in bucket

### ISSUE THREAD

**Issue by Powersource** [cobudget/cobudget#819]
Reported by @francesca-sp 

Payment metadata

```
{"contributionInCurrency":"3.00","currency":"eur","bucketId":"cl7g908s8068809l6dlxua5wg","roundSlug":"direkt-funding-test-round","directFundingType":"DONATION","userId":"ckx7m2u5x000008lmbd86jl5k","userEmail":"francesca@greaterthan.works"}
```

**Comment by Powersource** [comment]
Payment intent https://dashboard.stripe.com/connect/accounts/acct_1LcUWi2VnvGC2c77/payments/pi_3LckMS2VnvGC2c771h5ZJdlc

That page says "Pending webhook responseA webhook that is subscribed to the event hasn't successfully responded yet" in an info box

**Comment by Powersource** [comment]
No errors logged from vercel

**Comment by Powersource** [comment]
Ha! Found the error on the webhook page on stripe

```
Webhook Error: No signatures found matching the expected signature for payload. Are you passing the raw request body you received from Stripe? https://github.com/stripe/stripe-node#webhook-signing
```

https://dashboard.stripe.com/webhooks/we_1LVXjDFROlXOf2Bw5tXIV98y

**Comment by francesca-sp** [comment]
it worked! I contributed 2 € here: https://cobudget.com/greaterthan/direkt-funding-test-round/cl7g908s8068809l6dlxua5wg?tab=bucket

Would it be possible though to add the same notification that pops up when you contribute with your balance, the one that says "You contributed X successfully"? I think that would help create reassurance that the transaction worked. 

Also: is it normal that users don't get a notification email saying they contributed successfully? Is this something we could setup through stripe? Or would that need to be another notification email we add? I somehow think that when you make a real money transaction, it's important etiquette to receive a confirmation email.

**Comment by Powersource** [comment]
Great that it works!

The notification is planned in this issue https://github.com/cobudget/cobudget/issues/769#issuecomment-1242213254

We could easily add a notification email. Please describe it in a new issue.

**Comment by francesca-sp** [comment]
done @Powersource , and assigned you to the issue!
