### ISSUE TITLE
[MINOR] Make the Round table view available to non-admins, too

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#837]
**Describe the idea**

Currently, the table view (as opposed to the grid view) on the Round page is only available to admins. 

This view and information is useful when making budget allocation decisions, so why not make it available for all users? 
What do you think @aerugo and others?

**Comment by aerugo** [comment]
We had some doubts about performance issues, but maybe it's not a problem with server side rendering. What do you think @gustavlrsn, should we enable it for all users?

**Comment by gustavlrsn** [comment]
@aerugo I think it's safe to enable it, the query was optimized to avoid the n+1 problem

**Comment by francesca-sp** [comment]
This looks good!
