### ISSUE TITLE
[BUG] Drag-and-drop for budget re-ordering doesn't work 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#842]
**Describe the bug**

There are "re-order" icons on the Budget UI but once you let go of selecting it, the line goes back to where it was. 

See video: 
https://www.loom.com/share/1e0bf35a4b9a4055aa174a39d2707f54

**To Reproduce**

1. Go to a Bucket that you can edit 
2. Open the Budget section 
3. Try to drag and drop one of the line items 
4. It pops back to its original location 

**Expected behavior**

That I can drag to re-order the lines in my budget. 

**Browser and device (please complete the following information):**

- Browser [e.g. chrome, safari], and version if applicable

Mac, Chrome

**Comment by eden13** [comment]
working now! thanks!
