### ISSUE TITLE
[BUG] A bucket that is 10e short shows up as 100% funded 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#848]
**Describe the bug**

So this bucket has a budget of 2,600 euro. 

<img width="883" alt="Screenshot 2022-09-28 at 19 03 56" src="https://user-images.githubusercontent.com/1287179/192844887-47b71a24-06c7-421c-b2e1-b421911aeca6.png">

It has received 2590 euro — 10e short. 

<img width="402" alt="Screenshot 2022-09-28 at 19 01 57" src="https://user-images.githubusercontent.com/1287179/192844594-c37009a5-b3ac-465d-8d36-678c32839b7b.png">

<img width="384" alt="Screenshot 2022-09-28 at 18 59 41" src="https://user-images.githubusercontent.com/1287179/192844618-3b63923f-c470-461c-bdb8-b01cb6356364.png">

However, on the Round page (both grid and table view) it shows up as 100% funded. 

<img width="402" alt="Screenshot 2022-09-28 at 18 59 53" src="https://user-images.githubusercontent.com/1287179/192844765-9f168be8-8bf2-4be3-9606-7e5c32602987.png">

<img width="1206" alt="Screenshot 2022-09-28 at 18 58 55" src="https://user-images.githubusercontent.com/1287179/192844780-e84fb5ab-7193-4976-afcc-a9edcf4681d3.png">

**To Reproduce**

I haven't tried reproducing it, here is the bucket in question: 
https://cobudget.com/greaterthan/hike-2-2022/cl8ejkhew032609mcm3q9dru8?tab=bucket

**Comment by aerugo** [comment]
Ah right, yes this is a rounding edge case.
We need to treat numbers larger or equal than 99.5 but smaller than 100 as 99 and not 100.
It’s an easy fix.

**Comment by tomomiq** [comment]
LGTM 

<img width="1307" alt="Screenshot 2022-12-20 at 15 49 13" src="https://user-images.githubusercontent.com/1287179/208694734-841c1ac6-c416-4229-bad8-776714cc6d38.png">
