### ISSUE TITLE
[MINOR] Unify how Euro is displayed across the platform

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#849]
**Describe the idea**

Currently there are three ways to express Euro. 

* 1800€
* €1,800.00
* 18 000 EUR

After a fair amount of debate and looking at other services, @francesca-sp @eden-gt @DavidsBees and I want to propose unifying everything to the €1,800.00 format. 

And these rules for other currencies as well but that could be a separate issue / deprioritized if it means Euro is cleaned up! @aerugo what do you think? 

* Currency symbol at the front 
* Comma as the 1,000 separator 
* Dot for the decimal point

**Comment by francesca-sp** [comment]
Is it really that much more complicated to do this for all currencies at once? I don't really see the point in doing it only for Euro.

**Comment by aerugo** [comment]
I know there are JS libraries that already know how currencies are formatted and do it correctly. We should use one of those.

**Comment by Powersource** [comment]
I think we're already using our localization library for formatting of some of these, I think it's simplest if we just expand that to all cases.

**Comment by aerugo** [comment]
@alinauroz - the task here is to use a library everywhere we display any currency and let that library handle how the currency is displayed according to its standards.

**Comment by francesca-sp** [comment]
This looks good everywhere now, except for the main round page, where it is still in a different format, see screenshot. @alinauroz 
![image](https://user-images.githubusercontent.com/3641828/203378081-e2af8be1-4c8b-4c8a-859b-e4932da6c21a.png)

**Comment by alinauroz** [comment]
> This looks good everywhere now, except for the main round page, where it is still in a different format, see screenshot. @alinauroz ![image](https://user-images.githubusercontent.com/3641828/203378081-e2af8be1-4c8b-4c8a-859b-e4932da6c21a.png)

alright, I'll fix it.

**Comment by aerugo** [comment]
@alinauroz - this still needs to be fixed

**Comment by alinauroz** [comment]
> @alinauroz - this still needs to be fixed

Done

**Comment by tomomiq** [comment]
Yaaaa looks great, happy to have this!
