### ISSUE TITLE
[BUG] Superadmins can not see hidden rounds

### ISSUE THREAD

**Issue by alinauroz** [cobudget/cobudget#852]
**Describe the bug**
Superadmins can not see hidden round

**To Reproduce**

1. Start superadmin session
2. Open hidden round
3. Round is not visible

**Expected behavior**
Superadmin should have access to the hidden round

**Comment by tomomiq** [comment]
I made a hidden round - can someone check that you CAN see it as a super admin? 
https://cobudget.com/c/hiddenround
