### ISSUE TITLE
[BUG]  Strect Goal progress is NaN when there is no goal

### ISSUE THREAD

**Issue by alinauroz** [cobudget/cobudget#855]
**Describe the bug**
When stretch goal is enabled for a round but there is no goal set for a bucket, stretch goal progress is shown as `NaN%` in table view

**To Reproduce**

1. Create a round with stretch goals enabled
2. Add buckets
3. Open round and switch to table view

**Expected behavior**
Should show `0%` instead of `NaN%`

**Comment by tomomiq** [comment]
Great 

<img width="1412" alt="Screenshot 2022-10-11 at 15 55 43" src="https://user-images.githubusercontent.com/1287179/195110720-ba10ce14-2fe5-4824-b0ab-620961db9e4e.png">
