### ISSUE TITLE
[BUG] When managing member balance: [GraphQL] Cannot destructure property 'roundId' of 'undefined' as it is undefined.

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#860]
**Describe the bug**

When Adding or Setting the balance, it throws this error: 
> [GraphQL] Cannot destructure property 'roundId' of 'undefined' as it is undefined.

**To Reproduce**

1. Go to 'https://staging.cobudget.com/test-abc/test-round-abc
2. Click on the plus sign next to Balance 
3. Add money, click done 

**Screenshots**

<img width="1353" alt="Screenshot 2022-10-03 at 15 33 47" src="https://user-images.githubusercontent.com/1287179/193590823-7a0ae447-33c2-4a4b-9aff-0c1f46e0adf1.png">

**Additional context**

* I created a fresh group and got the same error, so assume it's not related a setting on the group "test-abc". 
* I have only tested on Staging.

**Comment by aerugo** [comment]
This seems to work on production, so it looks like it was introduced by a recent change. @alinauroz - any ideas?

**Comment by alinauroz** [comment]
@aerugo correct, it was introduced by refactoring resolvers.

**Comment by tomomiq** [comment]
Allocation successful 

<img width="1412" alt="Screenshot 2022-10-11 at 15 58 00" src="https://user-images.githubusercontent.com/1287179/195111441-7fb7164d-796a-4dd6-99bf-825b38567054.png">
