### ISSUE TITLE
[FEATURE] Add voluntary check box for emails

### ISSUE THREAD

**Issue by skoteskote** [cobudget/cobudget#864]
**Describe the feature**
When the user signs up we should ask them if they would like occasional emails about product updates and Cobudget-related events. 
This need to be saved in the database so we know what users have opted in for emails. 

Wording of checkbox:
"I would like occasional emails about product updates and Cobudget-related events, trainings, and support resources."

**Comment by tomomiq** [comment]
Let's prioritize @aerugo as we currently have no opt-in mechanism for marketing email comms?

**Comment by francesca-sp** [comment]
I don't see this checkbox as having been added anywhere. There is still only the accepting of the privacy policy. @Powersource why did you add needs testing? What has been added here? 

![image](https://user-images.githubusercontent.com/3641828/201946623-07273704-8c17-456c-83bd-02db157cdb6b.png)

**Comment by francesca-sp** [comment]
This works, but one comment about design: 
* Could we please make both checkboxes be the same font size
* and make the "ticks" in the checkbox both be blue, not in two different colors? 

![image](https://user-images.githubusercontent.com/3641828/201947580-bbe0488a-5481-4285-9386-9a2212273850.png) @alinauroz @Powersource

**Comment by alinauroz** [comment]
> This works, but one comment about design:
> 
> * Could we please make both checkboxes be the same font size
> * and make the "ticks" in the checkbox both be blue, not in two different colors?
> 
> @alinauroz @Powersource

@francesca-sp  does this look fine?


<img width="600" alt="Screenshot 2022-11-16 at 12 06 45 AM" src="https://user-images.githubusercontent.com/38759611/202004874-79e40322-defe-4de0-b71c-e8bde089ccb0.png">

The check marks are of the same font-size as the text. The borders make them look a little bit bigger.

**Comment by alinauroz** [comment]
<img width="489" alt="Screenshot 2022-11-16 at 12 16 47 AM" src="https://user-images.githubusercontent.com/38759611/202006356-dfbe7f74-7e58-488b-b1c4-9f387f159bac.png">

Check marks smaller than text look like this

**Comment by francesca-sp** [comment]
Great @alinauroz! One last small thing - could the first checkmark be aligned with the first line of text, rather than be centered? Thanks!

**Comment by alinauroz** [comment]
> could the first checkmark be aligned with the first line of text, rather than be centered?

Yes, sure

**Comment by francesca-sp** [comment]
This looks good now and ready to go!
