### ISSUE TITLE
[BUG] Bucket form page throws an Application error 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#867]
**Describe the bug**

I had this page open last Friday without any problems, not sure what's changed? 

<img width="1308" alt="Screenshot 2022-10-10 at 15 21 31" src="https://user-images.githubusercontent.com/1287179/194876450-f311cbdf-84f6-4a91-adcd-97595f7d4f68.png">

<img width="1308" alt="Screenshot 2022-10-10 at 15 22 14" src="https://user-images.githubusercontent.com/1287179/194876437-6d199757-96d8-496b-9dfc-c3816b7f4442.png">

**To Reproduce**

1. Open my bucket page, where I am an admin https://cobudget.com/greaterthan/hike-2-2022/
2. Settings > Bucket Form 

Or direct to https://cobudget.com/greaterthan/hike-2-2022/settings/bucket-form

**Comment by francesca-sp** [comment]
@alinauroz @aerugo FYI I got this same bug submitted through Enspiral as well, this is definitely broken on all rounds it seems.

**Comment by aerugo** [comment]
Thanks for the fix @alinauroz
