### ISSUE TITLE
too many emails

### ISSUE THREAD

**Issue by dominictarr** [cobudget/cobudget#87]
cobudget is sending me daily emails when I have already allocated all my funds.

It doesn't do me much good to be notified about new buckets, if I have nothing to put in them.
Once I get more funds, then i'll see the current buckets, so I don't need a daily notification.

**Comment by jessykate** [comment]
@dominictarr sorry, this was a year ago. do you still feel like you receive too many emails from cobudget?

**Comment by dominictarr** [comment]
no I don't get them anymore. memory is hazy, maybe i turned them off or filtered them? (or the policy changed?)

**Comment by jessykate** [comment]
ok, i'll close this for now but feel free to let us know if it's an issue for you again.
