### ISSUE TITLE
Setup ii codev pipeline

### ISSUE THREAD

**Issue by hh** [cobudget/cobudget#88]
I'd like to get pair programming env (koding), testing, and  delivery pipeline setup at gitlab.ii.org.nz

Will start on this tomorrow but would appreciate any help / pointers to setting things up.

**Comment by hh** [comment]
@gardner Looking forward to hooking this up all the way from src to load test. 8)

**Comment by gardner** [comment]
I am slammed for the next 2 weeks. Let's schedule a call for the 20th or 21st.

**Comment by hh** [comment]
Fun for fun.... what happens when you run the tests without mailcatcher:

![image](https://cloud.githubusercontent.com/assets/31331/18492686/bdb86d7c-7a60-11e6-9dd9-026e36304811.png)

I think we'll be getting these retries for a week or so:

![image](https://cloud.githubusercontent.com/assets/31331/18492719/d5bc1afe-7a60-11e6-8785-92e5d4fed405.png)

**Comment by jessykate** [comment]
hello, i am not sure what this is exactly. closing for now - can you re-open a ticket if this is still relevant?

**Comment by hh** [comment]
We were offering to help setup some hosted CI.
Maybe we can look at this again when you have interest in CI/CD.
See https://about.gitlab.com/gitlab-ci/

**Comment by gardner** [comment]
@hh meet @jessykate she's an enspiralite as well and is a driving force behind the Embassy Network. Hippie Hacker runs a software development collective in NZ and is passionate about continuous integration and continuous deployment, which is what this ticket is about.
