### ISSUE TITLE
[BUG] Cancelled bucket filter is not working 

### ISSUE THREAD

**Issue by tomomiq** [cobudget/cobudget#887]
**Describe the bug**

When there are "Cancelled" buckets, and it's unchecked in the filter, the cancelled buckets still show up in the Round page. 

<img width="1440" alt="Screenshot 2022-10-28 at 15 05 37" src="https://user-images.githubusercontent.com/1287179/198598736-f0e48417-1efd-44d3-a3bc-dcc5f3533d10.png">

**To Reproduce**

Can be re-produced here: 
https://cobudget.com/greaterthan/hike-2-2022

**Expected behavior**

For cancelled buckets to not be displayed, when the checkbox if ticked.

**Comment by francesca-sp** [comment]
Looks good, can be pushed!
