### ISSUE TITLE
Support adding money to bucket via Kiwibank Instant Deposits

### ISSUE THREAD

**Issue by hh** [cobudget/cobudget#89]
https://github.com/infertux/weboob-kiwibank

https://blog.rhysgoodwin.com/windows-desktop/auto-download-kiwibank-transactions-with-selenium/

**Comment by hh** [comment]
```feature
In order to support open source financially
A backer should be able to send money directly to a bucket

Given a bucket I want to support
When I send a direct payment to the account and number of a bucket
Then the funds are available to that project
```

**Comment by hh** [comment]
For iteration will only support Kiwibank

**Comment by hh** [comment]
I commented on a seemingly relevant trello ticket at: https://trello.com/c/VEqA8ITY @gardner @joshuavial but could probably use some intro on how ii can best help @cobudget continuously collaborate on issues like these

**Comment by hh** [comment]
@joshuavial @gardner @ii was looking into picking this up next week, is there anyone working on something similar? /cc @cobudget @kiwibank @rabble @ndorfin

**Comment by hh** [comment]
Cross posted to: https://twitter.com/hippiehacker/status/772627201111961600

**Comment by hh** [comment]
@joshuavial @gardner I've gotten @kiwibank on the line, but I'd still like to try coordinating something with @cobudget if this seems like something of value

https://twitter.com/KiwibankNZ/status/780863065755713536

![image](https://cloud.githubusercontent.com/assets/31331/18893193/4dfa8524-8569-11e6-87af-7f14b0030fda.png)

**Comment by jessykate** [comment]
hi @hh. this is neat! for general usage, most of our users are not kiwibank users. i think it would make more sense to have an intermediate payment handler like stripe or paypal in here, which is definitely on our list. otherwise, i'm not sure how adding individual banks would enable actual payments, do you have an idea or tool for doing this (that doesn't involve selenium :))?

**Comment by hh** [comment]
We were mainly trying to find a point of contact, and at the time (at osos.nz) there was a lot of discussion around kiwibank.

**Comment by jessykate** [comment]
ahh, that makes sense, thanks. i'll close this for now but we have some payment-related tickets in the backlog which may be of interest.
