### ISSUE TITLE
[BUG] Issue with filtering by status

### ISSUE THREAD

**Issue by francesca-sp** [cobudget/cobudget#898]
**Describe the bug**
In the Enspiral Cobudget round, buckets that are in the status "cancelled" are being shown when the filter is set to "pending approval". See screenshot, and this link here (with superadmin rights): https://cobudget.com/enspiral/funding-round-2022

![image](https://user-images.githubusercontent.com/3641828/204028014-ccba6662-6f1a-43fb-a160-b064850cf3fd.png)

**Expected behavior**
When the bucket status is "cancelled", one expects this bucket to only show up when the filter is selected to be "cancelled" (and not show up for any other statuses).

**Comment by DavidsBees** [comment]
This works now for me @alinauroz @francesca-sp @aerugo , thanks!
Not sure whether this was a group specific bug though - had a hard time reproducing it so i first thought its specific bug to this group ^^
